// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: activity.sql

package repository

import (
	"context"
)

const countListAuditLogs = `-- name: CountListAuditLogs :one
SELECT COUNT(*)
FROM activity_log log
JOIN "user" u ON u.id = log.actor_id
`

func (q *Queries) CountListAuditLogs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countListAuditLogs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAuditLog = `-- name: GetAuditLog :one
SELECT log.id, log.actor_id, log.target_user_id, log.target_menu_id, log.target_order_id, log.action_type, log.object_type, log.diff, log.ts, au.id, au.name, au.email, au.phone, au.role, au.picture, au.created_at, au.deleted_at, tu.id, tu.name, tu.email, tu.phone, tu.role, tu.picture, tu.created_at, tu.deleted_at,
    tu.id, tu.name, tu.email, tu.phone, tu.role, tu.picture, tu.created_at, tu.deleted_at, mi.id, mi.name, mi.description, mi.price, mi.picture, mi.category, mi.status, mi.ingredients, mi.created_at, mi.updated_at, o.id, o.waiter_id, o.status, o.table_number, o.note, o.total_price, o.created_at, o.delivered_at, o.updated_at, o.id, o.waiter_id, o.status, o.table_number, o.note, o.total_price, o.created_at, o.delivered_at, o.updated_at
FROM activity_log log
JOIN "user" au ON au.id = log.actor_id
LEFT JOIN menu_item mi ON mi.id = log.target_menu_item_id
LEFT JOIN "order" o ON o.id = log.target_order_id
LEFT JOIN "user" tu ON tu.id = log.target_user_id
LEFT JOIN "order" o ON o.id = log.target_order_id
WHERE log.id = $1
`

type GetAuditLogRow struct {
	ActivityLog ActivityLog `db:"activity_log" json:"activity_log"`
	User        User        `db:"user" json:"user"`
	User_2      User        `db:"user_2" json:"user_2"`
	User_3      User        `db:"user_3" json:"user_3"`
	MenuItem    MenuItem    `db:"menu_item" json:"menu_item"`
	Order       Order       `db:"order" json:"order"`
}

func (q *Queries) GetAuditLog(ctx context.Context, id int32) (GetAuditLogRow, error) {
	row := q.db.QueryRow(ctx, getAuditLog, id)
	var i GetAuditLogRow
	err := row.Scan(
		&i.ActivityLog.ID,
		&i.ActivityLog.ActorID,
		&i.ActivityLog.TargetUserID,
		&i.ActivityLog.TargetMenuID,
		&i.ActivityLog.TargetOrderID,
		&i.ActivityLog.ActionType,
		&i.ActivityLog.ObjectType,
		&i.ActivityLog.Diff,
		&i.ActivityLog.Ts,
		&i.User.ID,
		&i.User.Name,
		&i.User.Email,
		&i.User.Phone,
		&i.User.Role,
		&i.User.Picture,
		&i.User.CreatedAt,
		&i.User.DeletedAt,
		&i.User_2.ID,
		&i.User_2.Name,
		&i.User_2.Email,
		&i.User_2.Phone,
		&i.User_2.Role,
		&i.User_2.Picture,
		&i.User_2.CreatedAt,
		&i.User_2.DeletedAt,
		&i.User_3.ID,
		&i.User_3.Name,
		&i.User_3.Email,
		&i.User_3.Phone,
		&i.User_3.Role,
		&i.User_3.Picture,
		&i.User_3.CreatedAt,
		&i.User_3.DeletedAt,
		&i.MenuItem.ID,
		&i.MenuItem.Name,
		&i.MenuItem.Description,
		&i.MenuItem.Price,
		&i.MenuItem.Picture,
		&i.MenuItem.Category,
		&i.MenuItem.Status,
		&i.MenuItem.Ingredients,
		&i.MenuItem.CreatedAt,
		&i.MenuItem.UpdatedAt,
		&i.Order.ID,
		&i.Order.WaiterID,
		&i.Order.Status,
		&i.Order.TableNumber,
		&i.Order.Note,
		&i.Order.TotalPrice,
		&i.Order.CreatedAt,
		&i.Order.DeliveredAt,
		&i.Order.UpdatedAt,
	)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO activity_log (
    actor_id, target_user_id, target_menu_id, diff,
    action_type, object_type, target_order_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertAuditLogParams struct {
	ActorID       int32  `db:"actor_id" json:"actor_id"`
	TargetUserID  *int32 `db:"target_user_id" json:"target_user_id"`
	TargetMenuID  *int32 `db:"target_menu_id" json:"target_menu_id"`
	Diff          []byte `db:"diff" json:"diff"`
	ActionType    string `db:"action_type" json:"action_type"`
	ObjectType    string `db:"object_type" json:"object_type"`
	TargetOrderID *int32 `db:"target_order_id" json:"target_order_id"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.ActorID,
		arg.TargetUserID,
		arg.TargetMenuID,
		arg.Diff,
		arg.ActionType,
		arg.ObjectType,
		arg.TargetOrderID,
	)
	return err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT log.id, log.actor_id, log.target_user_id, log.target_menu_id, log.target_order_id, log.action_type, log.object_type, log.diff, log.ts, au.id, au.name, au.email, au.phone, au.role, au.picture, au.created_at, au.deleted_at, tu.id, tu.name, tu.email, tu.phone, tu.role, tu.picture, tu.created_at, tu.deleted_at,
    tu.id, tu.name, tu.email, tu.phone, tu.role, tu.picture, tu.created_at, tu.deleted_at, mi.id, mi.name, mi.description, mi.price, mi.picture, mi.category, mi.status, mi.ingredients, mi.created_at, mi.updated_at, o.id, o.waiter_id, o.status, o.table_number, o.note, o.total_price, o.created_at, o.delivered_at, o.updated_at, o.id, o.waiter_id, o.status, o.table_number, o.note, o.total_price, o.created_at, o.delivered_at, o.updated_at
FROM activity_log log
JOIN "user" au ON au.id = log.actor_id
LEFT JOIN menu_item mi ON mi.id = log.target_menu_item_id
LEFT JOIN "order" o ON o.id = log.target_order_id
LEFT JOIN "user" tu ON tu.id = log.target_user_id
LEFT JOIN "order" o ON o.id = log.target_order_id
ORDER BY log.ts DESC
LIMIT $2 OFFSET $1
`

type ListAuditLogsParams struct {
	Offset int32 `db:"offset" json:"offset"`
	Limit  int32 `db:"limit" json:"limit"`
}

type ListAuditLogsRow struct {
	ActivityLog ActivityLog `db:"activity_log" json:"activity_log"`
	User        User        `db:"user" json:"user"`
	User_2      User        `db:"user_2" json:"user_2"`
	User_3      User        `db:"user_3" json:"user_3"`
	MenuItem    MenuItem    `db:"menu_item" json:"menu_item"`
	Order       Order       `db:"order" json:"order"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogs, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogsRow{}
	for rows.Next() {
		var i ListAuditLogsRow
		if err := rows.Scan(
			&i.ActivityLog.ID,
			&i.ActivityLog.ActorID,
			&i.ActivityLog.TargetUserID,
			&i.ActivityLog.TargetMenuID,
			&i.ActivityLog.TargetOrderID,
			&i.ActivityLog.ActionType,
			&i.ActivityLog.ObjectType,
			&i.ActivityLog.Diff,
			&i.ActivityLog.Ts,
			&i.User.ID,
			&i.User.Name,
			&i.User.Email,
			&i.User.Phone,
			&i.User.Role,
			&i.User.Picture,
			&i.User.CreatedAt,
			&i.User.DeletedAt,
			&i.User_2.ID,
			&i.User_2.Name,
			&i.User_2.Email,
			&i.User_2.Phone,
			&i.User_2.Role,
			&i.User_2.Picture,
			&i.User_2.CreatedAt,
			&i.User_2.DeletedAt,
			&i.User_3.ID,
			&i.User_3.Name,
			&i.User_3.Email,
			&i.User_3.Phone,
			&i.User_3.Role,
			&i.User_3.Picture,
			&i.User_3.CreatedAt,
			&i.User_3.DeletedAt,
			&i.MenuItem.ID,
			&i.MenuItem.Name,
			&i.MenuItem.Description,
			&i.MenuItem.Price,
			&i.MenuItem.Picture,
			&i.MenuItem.Category,
			&i.MenuItem.Status,
			&i.MenuItem.Ingredients,
			&i.MenuItem.CreatedAt,
			&i.MenuItem.UpdatedAt,
			&i.Order.ID,
			&i.Order.WaiterID,
			&i.Order.Status,
			&i.Order.TableNumber,
			&i.Order.Note,
			&i.Order.TotalPrice,
			&i.Order.CreatedAt,
			&i.Order.DeliveredAt,
			&i.Order.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
