// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: activity.sql

package repository

import (
	"context"
	"time"

	types "restaurant-server/shared/types"
)

const countListAuditLogs = `-- name: CountListAuditLogs :one
SELECT COUNT(*)
FROM activity_log log
JOIN "user" u ON u.id = log.actor_id
`

func (q *Queries) CountListAuditLogs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countListAuditLogs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAuditLog = `-- name: GetAuditLog :one
SELECT log.id, log.actor_id, log.target_user_id, log.target_user_name, log.target_menu_id, log.target_menu_name, log.target_order_id, log.action_type, log.object_type, log.diff, log.ts, au.name AS actor_name, au.role AS actor_role
FROM activity_log log
JOIN "user" au ON au.id = log.actor_id
WHERE log.id = $1
`

type GetAuditLogRow struct {
	ID             int32       `db:"id" json:"id"`
	ActorID        int32       `db:"actor_id" json:"actor_id"`
	TargetUserID   *int32      `db:"target_user_id" json:"target_user_id"`
	TargetUserName *string     `db:"target_user_name" json:"target_user_name"`
	TargetMenuID   *int32      `db:"target_menu_id" json:"target_menu_id"`
	TargetMenuName *string     `db:"target_menu_name" json:"target_menu_name"`
	TargetOrderID  *int32      `db:"target_order_id" json:"target_order_id"`
	ActionType     string      `db:"action_type" json:"action_type"`
	ObjectType     string      `db:"object_type" json:"object_type"`
	Diff           types.JSONB `db:"diff" json:"diff"`
	Ts             time.Time   `db:"ts" json:"ts"`
	ActorName      string      `db:"actor_name" json:"actor_name"`
	ActorRole      string      `db:"actor_role" json:"actor_role"`
}

func (q *Queries) GetAuditLog(ctx context.Context, id int32) (GetAuditLogRow, error) {
	row := q.db.QueryRow(ctx, getAuditLog, id)
	var i GetAuditLogRow
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.TargetUserID,
		&i.TargetUserName,
		&i.TargetMenuID,
		&i.TargetMenuName,
		&i.TargetOrderID,
		&i.ActionType,
		&i.ObjectType,
		&i.Diff,
		&i.Ts,
		&i.ActorName,
		&i.ActorRole,
	)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO activity_log (
    actor_id, target_user_id, target_menu_id, diff,
    action_type, object_type, target_order_id,
    target_user_name, target_menu_name
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertAuditLogParams struct {
	ActorID        int32       `db:"actor_id" json:"actor_id"`
	TargetUserID   *int32      `db:"target_user_id" json:"target_user_id"`
	TargetMenuID   *int32      `db:"target_menu_id" json:"target_menu_id"`
	Diff           types.JSONB `db:"diff" json:"diff"`
	ActionType     string      `db:"action_type" json:"action_type"`
	ObjectType     string      `db:"object_type" json:"object_type"`
	TargetOrderID  *int32      `db:"target_order_id" json:"target_order_id"`
	TargetUserName *string     `db:"target_user_name" json:"target_user_name"`
	TargetMenuName *string     `db:"target_menu_name" json:"target_menu_name"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.ActorID,
		arg.TargetUserID,
		arg.TargetMenuID,
		arg.Diff,
		arg.ActionType,
		arg.ObjectType,
		arg.TargetOrderID,
		arg.TargetUserName,
		arg.TargetMenuName,
	)
	return err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT log.id, log.actor_id, log.target_user_id, log.target_user_name, log.target_menu_id, log.target_menu_name, log.target_order_id, log.action_type, log.object_type, log.diff, log.ts, au.name AS actor_name, au.role AS actor_role
FROM activity_log log
JOIN "user" au ON au.id = log.actor_id
ORDER BY log.ts DESC
LIMIT $2 OFFSET $1
`

type ListAuditLogsParams struct {
	Offset int32 `db:"offset" json:"offset"`
	Limit  int32 `db:"limit" json:"limit"`
}

type ListAuditLogsRow struct {
	ID             int32       `db:"id" json:"id"`
	ActorID        int32       `db:"actor_id" json:"actor_id"`
	TargetUserID   *int32      `db:"target_user_id" json:"target_user_id"`
	TargetUserName *string     `db:"target_user_name" json:"target_user_name"`
	TargetMenuID   *int32      `db:"target_menu_id" json:"target_menu_id"`
	TargetMenuName *string     `db:"target_menu_name" json:"target_menu_name"`
	TargetOrderID  *int32      `db:"target_order_id" json:"target_order_id"`
	ActionType     string      `db:"action_type" json:"action_type"`
	ObjectType     string      `db:"object_type" json:"object_type"`
	Diff           types.JSONB `db:"diff" json:"diff"`
	Ts             time.Time   `db:"ts" json:"ts"`
	ActorName      string      `db:"actor_name" json:"actor_name"`
	ActorRole      string      `db:"actor_role" json:"actor_role"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogs, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogsRow{}
	for rows.Next() {
		var i ListAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.TargetUserID,
			&i.TargetUserName,
			&i.TargetMenuID,
			&i.TargetMenuName,
			&i.TargetOrderID,
			&i.ActionType,
			&i.ObjectType,
			&i.Diff,
			&i.Ts,
			&i.ActorName,
			&i.ActorRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
