// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: analytics.sql

package repository

import (
	"context"
)

const avgPreparationTimeDaily = `-- name: AvgPreparationTimeDaily :one
SELECT COALESCE(AVG(EXTRACT(EPOCH FROM (delivered_at - created_at))), 0) AS avg_prep_seconds
FROM "order"
WHERE status = 'delivered'
AND DATE(created_at) = CURRENT_DATE
`

func (q *Queries) AvgPreparationTimeDaily(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRow(ctx, avgPreparationTimeDaily)
	var avg_prep_seconds interface{}
	err := row.Scan(&avg_prep_seconds)
	return avg_prep_seconds, err
}

const avgPreparationTimeMonthly = `-- name: AvgPreparationTimeMonthly :one
SELECT COALESCE(AVG(EXTRACT(EPOCH FROM (delivered_at - created_at))), 0) AS avg_prep_seconds
FROM "order"
WHERE status = 'delivered'
AND DATE_TRUNC('month', created_at) = DATE_TRUNC('month', CURRENT_DATE)
`

func (q *Queries) AvgPreparationTimeMonthly(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRow(ctx, avgPreparationTimeMonthly)
	var avg_prep_seconds interface{}
	err := row.Scan(&avg_prep_seconds)
	return avg_prep_seconds, err
}

const avgPreparationTimeWeekly = `-- name: AvgPreparationTimeWeekly :one
SELECT COALESCE(AVG(EXTRACT(EPOCH FROM (delivered_at - created_at))), 0) AS avg_prep_seconds
FROM "order"
WHERE status = 'delivered'
AND DATE_TRUNC('week', created_at) = DATE_TRUNC('week', CURRENT_DATE)
`

func (q *Queries) AvgPreparationTimeWeekly(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRow(ctx, avgPreparationTimeWeekly)
	var avg_prep_seconds interface{}
	err := row.Scan(&avg_prep_seconds)
	return avg_prep_seconds, err
}

const countCompletedOrdersDaily = `-- name: CountCompletedOrdersDaily :one
SELECT COUNT(*) AS total
FROM "order"
WHERE status = 'delivered'
  AND DATE(created_at) = CURRENT_DATE
`

func (q *Queries) CountCompletedOrdersDaily(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCompletedOrdersDaily)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countCompletedOrdersMonthly = `-- name: CountCompletedOrdersMonthly :one
SELECT COUNT(*) AS total
FROM "order"
WHERE status = 'delivered'
  AND DATE_TRUNC('month', created_at) = DATE_TRUNC('month', CURRENT_DATE)
`

func (q *Queries) CountCompletedOrdersMonthly(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCompletedOrdersMonthly)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countCompletedOrdersWeekly = `-- name: CountCompletedOrdersWeekly :one
SELECT COUNT(*) AS total
FROM "order"
WHERE status = 'delivered'
  AND DATE_TRUNC('week', created_at) = DATE_TRUNC('week', CURRENT_DATE)
`

func (q *Queries) CountCompletedOrdersWeekly(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCompletedOrdersWeekly)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getCompletedOrdersDaily = `-- name: GetCompletedOrdersDaily :many
SELECT id, waiter_id, status, table_number, note, total_price, created_at, delivered_at, updated_at
FROM "order"
WHERE status = 'delivered'
  AND DATE(created_at) = CURRENT_DATE
ORDER BY created_at DESC
`

func (q *Queries) GetCompletedOrdersDaily(ctx context.Context) ([]Order, error) {
	rows, err := q.db.Query(ctx, getCompletedOrdersDaily)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.WaiterID,
			&i.Status,
			&i.TableNumber,
			&i.Note,
			&i.TotalPrice,
			&i.CreatedAt,
			&i.DeliveredAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCompletedOrdersMonthly = `-- name: GetCompletedOrdersMonthly :many
SELECT id, waiter_id, status, table_number, note, total_price, created_at, delivered_at, updated_at
FROM "order"
WHERE status = 'delivered'
  AND DATE_TRUNC('month', created_at) = DATE_TRUNC('month', CURRENT_DATE)
ORDER BY created_at DESC
`

func (q *Queries) GetCompletedOrdersMonthly(ctx context.Context) ([]Order, error) {
	rows, err := q.db.Query(ctx, getCompletedOrdersMonthly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.WaiterID,
			&i.Status,
			&i.TableNumber,
			&i.Note,
			&i.TotalPrice,
			&i.CreatedAt,
			&i.DeliveredAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCompletedOrdersWeekly = `-- name: GetCompletedOrdersWeekly :many
SELECT id, waiter_id, status, table_number, note, total_price, created_at, delivered_at, updated_at
FROM "order"
WHERE status = 'delivered'
  AND DATE_TRUNC('week', created_at) = DATE_TRUNC('week', CURRENT_DATE)
ORDER BY created_at DESC
`

func (q *Queries) GetCompletedOrdersWeekly(ctx context.Context) ([]Order, error) {
	rows, err := q.db.Query(ctx, getCompletedOrdersWeekly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.WaiterID,
			&i.Status,
			&i.TableNumber,
			&i.Note,
			&i.TotalPrice,
			&i.CreatedAt,
			&i.DeliveredAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
