// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: auth.sql

package repository

import (
	"context"
)

const blockAccount = `-- name: BlockAccount :exec
UPDATE account
SET blocked = TRUE
WHERE account.user_id = $1
`

func (q *Queries) BlockAccount(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, blockAccount, userID)
	return err
}

const createAccount = `-- name: CreateAccount :exec
INSERT INTO account (user_id, password_hash)
VALUES ($1, $2)
`

type CreateAccountParams struct {
	UserID       int32  `db:"user_id" json:"user_id"`
	PasswordHash string `db:"password_hash" json:"password_hash"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) error {
	_, err := q.db.Exec(ctx, createAccount, arg.UserID, arg.PasswordHash)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT id, password_hash, invited, blocked, user_id, created_at, deleted_at FROM account
WHERE account.user_id = $1
`

func (q *Queries) GetAccount(ctx context.Context, userID int32) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, userID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.PasswordHash,
		&i.Invited,
		&i.Blocked,
		&i.UserID,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const unblockAccount = `-- name: UnblockAccount :exec
UPDATE account
SET blocked = FALSE
WHERE account.user_id = $1
`

func (q *Queries) UnblockAccount(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, unblockAccount, userID)
	return err
}
