// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: menu.sql

package repository

import (
	"context"
)

const createMenuItem = `-- name: CreateMenuItem :one
INSERT INTO menu_item (name, description, price, status, picture, category, ingredients)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, description, price, picture, category, status, ingredients, created_at, updated_at
`

type CreateMenuItemParams struct {
	Name        string   `db:"name" json:"name"`
	Description *string  `db:"description" json:"description"`
	Price       float64  `db:"price" json:"price"`
	Status      bool     `db:"status" json:"status"`
	Picture     string   `db:"picture" json:"picture"`
	Category    string   `db:"category" json:"category"`
	Ingredients []string `db:"ingredients" json:"ingredients"`
}

func (q *Queries) CreateMenuItem(ctx context.Context, arg CreateMenuItemParams) (MenuItem, error) {
	row := q.db.QueryRow(ctx, createMenuItem,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Status,
		arg.Picture,
		arg.Category,
		arg.Ingredients,
	)
	var i MenuItem
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Picture,
		&i.Category,
		&i.Status,
		&i.Ingredients,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMenuItem = `-- name: DeleteMenuItem :exec
DELETE FROM menu_item WHERE id = $1
`

func (q *Queries) DeleteMenuItem(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteMenuItem, id)
	return err
}

const getMenuItem = `-- name: GetMenuItem :one
SELECT id, name, description, price, picture, category, status, ingredients, created_at, updated_at FROM menu_item WHERE id = $1
`

func (q *Queries) GetMenuItem(ctx context.Context, id int32) (MenuItem, error) {
	row := q.db.QueryRow(ctx, getMenuItem, id)
	var i MenuItem
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Picture,
		&i.Category,
		&i.Status,
		&i.Ingredients,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveMenuItems = `-- name: ListActiveMenuItems :many
SELECT id, name, description, price, picture, category, status, ingredients, created_at, updated_at FROM menu_item WHERE status = TRUE ORDER BY created_at DESC
`

func (q *Queries) ListActiveMenuItems(ctx context.Context) ([]MenuItem, error) {
	rows, err := q.db.Query(ctx, listActiveMenuItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MenuItem{}
	for rows.Next() {
		var i MenuItem
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Picture,
			&i.Category,
			&i.Status,
			&i.Ingredients,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMenuItems = `-- name: ListMenuItems :many
SELECT id, name, description, price, picture, category, status, ingredients, created_at, updated_at FROM menu_item ORDER BY name ASC
`

func (q *Queries) ListMenuItems(ctx context.Context) ([]MenuItem, error) {
	rows, err := q.db.Query(ctx, listMenuItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MenuItem{}
	for rows.Next() {
		var i MenuItem
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Picture,
			&i.Category,
			&i.Status,
			&i.Ingredients,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMenuItem = `-- name: UpdateMenuItem :one
UPDATE menu_item
SET
    name = COALESCE($2, name),
    price = COALESCE($3, price),
    status = COALESCE($4, status),
    picture = COALESCE($5, picture),
    category = COALESCE($6, category),
    description = COALESCE($7, description),
    ingredients = COALESCE($8, ingredients),
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, description, price, picture, category, status, ingredients, created_at, updated_at
`

type UpdateMenuItemParams struct {
	ID          int32    `db:"id" json:"id"`
	Name        *string  `db:"name" json:"name"`
	Price       *float64 `db:"price" json:"price"`
	Status      *bool    `db:"status" json:"status"`
	Picture     *string  `db:"picture" json:"picture"`
	Category    *string  `db:"category" json:"category"`
	Description *string  `db:"description" json:"description"`
	Ingredients []string `db:"ingredients" json:"ingredients"`
}

func (q *Queries) UpdateMenuItem(ctx context.Context, arg UpdateMenuItemParams) (MenuItem, error) {
	row := q.db.QueryRow(ctx, updateMenuItem,
		arg.ID,
		arg.Name,
		arg.Price,
		arg.Status,
		arg.Picture,
		arg.Category,
		arg.Description,
		arg.Ingredients,
	)
	var i MenuItem
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Picture,
		&i.Category,
		&i.Status,
		&i.Ingredients,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
