// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"time"
)

type Account struct {
	ID           int32      `db:"id" json:"id"`
	PasswordHash string     `db:"password_hash" json:"password_hash"`
	Invited      bool       `db:"invited" json:"invited"`
	Blocked      bool       `db:"blocked" json:"blocked"`
	UserID       int32      `db:"user_id" json:"user_id"`
	CreatedAt    time.Time  `db:"created_at" json:"created_at"`
	DeletedAt    *time.Time `db:"deleted_at" json:"deleted_at"`
}

type ActivityLog struct {
	ID            int32     `db:"id" json:"id"`
	ActorID       int32     `db:"actor_id" json:"actor_id"`
	TargetUserID  *int32    `db:"target_user_id" json:"target_user_id"`
	TargetMenuID  *int32    `db:"target_menu_id" json:"target_menu_id"`
	TargetOrderID *int32    `db:"target_order_id" json:"target_order_id"`
	ActionType    string    `db:"action_type" json:"action_type"`
	ObjectType    string    `db:"object_type" json:"object_type"`
	Diff          []byte    `db:"diff" json:"diff"`
	Ts            time.Time `db:"ts" json:"ts"`
}

type MenuItem struct {
	ID          int32     `db:"id" json:"id"`
	Name        string    `db:"name" json:"name"`
	Description *string   `db:"description" json:"description"`
	Price       float64   `db:"price" json:"price"`
	Picture     string    `db:"picture" json:"picture"`
	Category    string    `db:"category" json:"category"`
	Status      bool      `db:"status" json:"status"`
	Ingredients []string  `db:"ingredients" json:"ingredients"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time `db:"updated_at" json:"updated_at"`
}

type Order struct {
	ID          int32      `db:"id" json:"id"`
	WaiterID    *int32     `db:"waiter_id" json:"waiter_id"`
	Status      string     `db:"status" json:"status"`
	TableNumber string     `db:"table_number" json:"table_number"`
	Note        *string    `db:"note" json:"note"`
	TotalPrice  float32    `db:"total_price" json:"total_price"`
	CreatedAt   time.Time  `db:"created_at" json:"created_at"`
	DeliveredAt *time.Time `db:"delivered_at" json:"delivered_at"`
	UpdatedAt   time.Time  `db:"updated_at" json:"updated_at"`
}

type OrderItem struct {
	ID         int32     `db:"id" json:"id"`
	OrderID    int32     `db:"order_id" json:"order_id"`
	MenuItemID int32     `db:"menu_item_id" json:"menu_item_id"`
	Quantity   int32     `db:"quantity" json:"quantity"`
	Price      float32   `db:"price" json:"price"`
	Category   string    `db:"category" json:"category"`
	CreatedAt  time.Time `db:"created_at" json:"created_at"`
	UpdatedAt  time.Time `db:"updated_at" json:"updated_at"`
}

type PasswordResetTokens struct {
	ID        int32      `db:"id" json:"id"`
	UserID    int32      `db:"user_id" json:"user_id"`
	Token     string     `db:"token" json:"token"`
	ExpiresAt time.Time  `db:"expires_at" json:"expires_at"`
	CreatedAt time.Time  `db:"created_at" json:"created_at"`
	UsedAt    *time.Time `db:"used_at" json:"used_at"`
}

type RefreshTokens struct {
	ID        int32     `db:"id" json:"id"`
	UserID    int32     `db:"user_id" json:"user_id"`
	Token     string    `db:"token" json:"token"`
	ExpiresAt time.Time `db:"expires_at" json:"expires_at"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

type User struct {
	ID        int32      `db:"id" json:"id"`
	Name      string     `db:"name" json:"name"`
	Email     string     `db:"email" json:"email"`
	Phone     string     `db:"phone" json:"phone"`
	Role      string     `db:"role" json:"role"`
	Picture   *string    `db:"picture" json:"picture"`
	CreatedAt time.Time  `db:"created_at" json:"created_at"`
	DeletedAt *time.Time `db:"deleted_at" json:"deleted_at"`
}
