// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: order.sql

package repository

import (
	"context"
	"time"
)

const addOrderItem = `-- name: AddOrderItem :one
INSERT INTO order_item (order_id, menu_item_id, quantity, price, category)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, order_id, menu_item_id, quantity, price, category, created_at, updated_at
`

type AddOrderItemParams struct {
	OrderID    int32   `db:"order_id" json:"order_id"`
	MenuItemID int32   `db:"menu_item_id" json:"menu_item_id"`
	Quantity   int32   `db:"quantity" json:"quantity"`
	Price      float32 `db:"price" json:"price"`
	Category   string  `db:"category" json:"category"`
}

func (q *Queries) AddOrderItem(ctx context.Context, arg AddOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, addOrderItem,
		arg.OrderID,
		arg.MenuItemID,
		arg.Quantity,
		arg.Price,
		arg.Category,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.MenuItemID,
		&i.Quantity,
		&i.Price,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const clearOrderItems = `-- name: ClearOrderItems :exec
DELETE FROM order_item WHERE order_id = $1
`

func (q *Queries) ClearOrderItems(ctx context.Context, orderID int32) error {
	_, err := q.db.Exec(ctx, clearOrderItems, orderID)
	return err
}

const countActiveOrders = `-- name: CountActiveOrders :one
SELECT COUNT(*)
FROM "order"
WHERE "order".status IN ('pending', 'processing', 'ready')
`

func (q *Queries) CountActiveOrders(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveOrders)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCancelledOrders = `-- name: CountCancelledOrders :one
SELECT COUNT(*)
FROM "order"
WHERE "order".status = 'cancelled'
`

func (q *Queries) CountCancelledOrders(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCancelledOrders)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDeliveredOrders = `-- name: CountDeliveredOrders :one
SELECT COUNT(*)
FROM "order"
WHERE "order".status = 'delivered'
`

func (q *Queries) CountDeliveredOrders(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDeliveredOrders)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingOrders = `-- name: CountPendingOrders :one
SELECT COUNT(*)
FROM "order"
WHERE "order".status = 'pending'
`

func (q *Queries) CountPendingOrders(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingOrders)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProcessingOrders = `-- name: CountProcessingOrders :one
SELECT COUNT(*)
FROM "order"
WHERE "order".status = 'processing'
`

func (q *Queries) CountProcessingOrders(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countProcessingOrders)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReadyOrders = `-- name: CountReadyOrders :one
SELECT COUNT(*)
FROM "order"
WHERE "order".status = 'ready'
`

func (q *Queries) CountReadyOrders(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countReadyOrders)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO "order" (waiter_id, status, table_number, total_price, note)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, waiter_id, status, table_number, note, total_price, created_at, delivered_at, updated_at
`

type CreateOrderParams struct {
	WaiterID    *int32  `db:"waiter_id" json:"waiter_id"`
	Status      string  `db:"status" json:"status"`
	TableNumber string  `db:"table_number" json:"table_number"`
	TotalPrice  float32 `db:"total_price" json:"total_price"`
	Note        *string `db:"note" json:"note"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.WaiterID,
		arg.Status,
		arg.TableNumber,
		arg.TotalPrice,
		arg.Note,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.WaiterID,
		&i.Status,
		&i.TableNumber,
		&i.Note,
		&i.TotalPrice,
		&i.CreatedAt,
		&i.DeliveredAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOrder = `-- name: DeleteOrder :exec
DELETE FROM "order" WHERE id = $1
`

func (q *Queries) DeleteOrder(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteOrder, id)
	return err
}

const deleteOrderItem = `-- name: DeleteOrderItem :exec
DELETE FROM order_item WHERE id = $1
`

func (q *Queries) DeleteOrderItem(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteOrderItem, id)
	return err
}

const getOrder = `-- name: GetOrder :one
SELECT o.id, o.waiter_id, o.status, o.table_number, o.note, o.total_price, o.created_at, o.delivered_at, o.updated_at, u.name AS waiter_name
FROM "order" o
LEFT JOIN "user" u ON o.waiter_id = u.id
WHERE o.id = $1
`

type GetOrderRow struct {
	ID          int32      `db:"id" json:"id"`
	WaiterID    *int32     `db:"waiter_id" json:"waiter_id"`
	Status      string     `db:"status" json:"status"`
	TableNumber string     `db:"table_number" json:"table_number"`
	Note        *string    `db:"note" json:"note"`
	TotalPrice  float32    `db:"total_price" json:"total_price"`
	CreatedAt   time.Time  `db:"created_at" json:"created_at"`
	DeliveredAt *time.Time `db:"delivered_at" json:"delivered_at"`
	UpdatedAt   time.Time  `db:"updated_at" json:"updated_at"`
	WaiterName  *string    `db:"waiter_name" json:"waiter_name"`
}

func (q *Queries) GetOrder(ctx context.Context, id int32) (GetOrderRow, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i GetOrderRow
	err := row.Scan(
		&i.ID,
		&i.WaiterID,
		&i.Status,
		&i.TableNumber,
		&i.Note,
		&i.TotalPrice,
		&i.CreatedAt,
		&i.DeliveredAt,
		&i.UpdatedAt,
		&i.WaiterName,
	)
	return i, err
}

const getOrderItems = `-- name: GetOrderItems :many
SELECT oi.id, oi.order_id, oi.menu_item_id, oi.quantity, oi.price, oi.category, oi.created_at, oi.updated_at, mi.name, mi.price
FROM order_item oi
JOIN menu_item mi ON oi.menu_item_id = mi.id
WHERE oi.order_id = $1
ORDER BY oi.created_at ASC
`

type GetOrderItemsRow struct {
	ID         int32     `db:"id" json:"id"`
	OrderID    int32     `db:"order_id" json:"order_id"`
	MenuItemID int32     `db:"menu_item_id" json:"menu_item_id"`
	Quantity   int32     `db:"quantity" json:"quantity"`
	Price      float32   `db:"price" json:"price"`
	Category   string    `db:"category" json:"category"`
	CreatedAt  time.Time `db:"created_at" json:"created_at"`
	UpdatedAt  time.Time `db:"updated_at" json:"updated_at"`
	Name       string    `db:"name" json:"name"`
	Price_2    float64   `db:"price_2" json:"price_2"`
}

func (q *Queries) GetOrderItems(ctx context.Context, orderID int32) ([]GetOrderItemsRow, error) {
	rows, err := q.db.Query(ctx, getOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOrderItemsRow{}
	for rows.Next() {
		var i GetOrderItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.MenuItemID,
			&i.Quantity,
			&i.Price,
			&i.Category,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Price_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCancelledOrders = `-- name: ListCancelledOrders :many
SELECT o.id, o.waiter_id, o.status, o.table_number, o.note, o.total_price, o.created_at, o.delivered_at, o.updated_at, u.name AS waiter_name
FROM "order" o
LEFT JOIN "user" u ON o.waiter_id = u.id
WHERE o.status = 'cancelled'
ORDER BY o.created_at ASC
LIMIT $2 OFFSET $1
`

type ListCancelledOrdersParams struct {
	Offset int32 `db:"offset" json:"offset"`
	Limit  int32 `db:"limit" json:"limit"`
}

type ListCancelledOrdersRow struct {
	ID          int32      `db:"id" json:"id"`
	WaiterID    *int32     `db:"waiter_id" json:"waiter_id"`
	Status      string     `db:"status" json:"status"`
	TableNumber string     `db:"table_number" json:"table_number"`
	Note        *string    `db:"note" json:"note"`
	TotalPrice  float32    `db:"total_price" json:"total_price"`
	CreatedAt   time.Time  `db:"created_at" json:"created_at"`
	DeliveredAt *time.Time `db:"delivered_at" json:"delivered_at"`
	UpdatedAt   time.Time  `db:"updated_at" json:"updated_at"`
	WaiterName  *string    `db:"waiter_name" json:"waiter_name"`
}

func (q *Queries) ListCancelledOrders(ctx context.Context, arg ListCancelledOrdersParams) ([]ListCancelledOrdersRow, error) {
	rows, err := q.db.Query(ctx, listCancelledOrders, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCancelledOrdersRow{}
	for rows.Next() {
		var i ListCancelledOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.WaiterID,
			&i.Status,
			&i.TableNumber,
			&i.Note,
			&i.TotalPrice,
			&i.CreatedAt,
			&i.DeliveredAt,
			&i.UpdatedAt,
			&i.WaiterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeliveredOrders = `-- name: ListDeliveredOrders :many
SELECT o.id, o.waiter_id, o.status, o.table_number, o.note, o.total_price, o.created_at, o.delivered_at, o.updated_at, u.name AS waiter_name
FROM "order" o
LEFT JOIN "user" u ON o.waiter_id = u.id
WHERE o.status = 'delivered'
ORDER BY o.delivered_at DESC
LIMIT $2 OFFSET $1
`

type ListDeliveredOrdersParams struct {
	Offset int32 `db:"offset" json:"offset"`
	Limit  int32 `db:"limit" json:"limit"`
}

type ListDeliveredOrdersRow struct {
	ID          int32      `db:"id" json:"id"`
	WaiterID    *int32     `db:"waiter_id" json:"waiter_id"`
	Status      string     `db:"status" json:"status"`
	TableNumber string     `db:"table_number" json:"table_number"`
	Note        *string    `db:"note" json:"note"`
	TotalPrice  float32    `db:"total_price" json:"total_price"`
	CreatedAt   time.Time  `db:"created_at" json:"created_at"`
	DeliveredAt *time.Time `db:"delivered_at" json:"delivered_at"`
	UpdatedAt   time.Time  `db:"updated_at" json:"updated_at"`
	WaiterName  *string    `db:"waiter_name" json:"waiter_name"`
}

func (q *Queries) ListDeliveredOrders(ctx context.Context, arg ListDeliveredOrdersParams) ([]ListDeliveredOrdersRow, error) {
	rows, err := q.db.Query(ctx, listDeliveredOrders, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeliveredOrdersRow{}
	for rows.Next() {
		var i ListDeliveredOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.WaiterID,
			&i.Status,
			&i.TableNumber,
			&i.Note,
			&i.TotalPrice,
			&i.CreatedAt,
			&i.DeliveredAt,
			&i.UpdatedAt,
			&i.WaiterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingOrders = `-- name: ListPendingOrders :many
SELECT o.id, o.waiter_id, o.status, o.table_number, o.note, o.total_price, o.created_at, o.delivered_at, o.updated_at, u.name AS waiter_name
FROM "order" o
LEFT JOIN "user" u ON o.waiter_id = u.id
WHERE o.status = 'pending'
ORDER BY o.created_at ASC
LIMIT $2 OFFSET $1
`

type ListPendingOrdersParams struct {
	Offset int32 `db:"offset" json:"offset"`
	Limit  int32 `db:"limit" json:"limit"`
}

type ListPendingOrdersRow struct {
	ID          int32      `db:"id" json:"id"`
	WaiterID    *int32     `db:"waiter_id" json:"waiter_id"`
	Status      string     `db:"status" json:"status"`
	TableNumber string     `db:"table_number" json:"table_number"`
	Note        *string    `db:"note" json:"note"`
	TotalPrice  float32    `db:"total_price" json:"total_price"`
	CreatedAt   time.Time  `db:"created_at" json:"created_at"`
	DeliveredAt *time.Time `db:"delivered_at" json:"delivered_at"`
	UpdatedAt   time.Time  `db:"updated_at" json:"updated_at"`
	WaiterName  *string    `db:"waiter_name" json:"waiter_name"`
}

func (q *Queries) ListPendingOrders(ctx context.Context, arg ListPendingOrdersParams) ([]ListPendingOrdersRow, error) {
	rows, err := q.db.Query(ctx, listPendingOrders, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingOrdersRow{}
	for rows.Next() {
		var i ListPendingOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.WaiterID,
			&i.Status,
			&i.TableNumber,
			&i.Note,
			&i.TotalPrice,
			&i.CreatedAt,
			&i.DeliveredAt,
			&i.UpdatedAt,
			&i.WaiterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProcessingOrders = `-- name: ListProcessingOrders :many
SELECT o.id, o.waiter_id, o.status, o.table_number, o.note, o.total_price, o.created_at, o.delivered_at, o.updated_at, u.name AS waiter_name
FROM "order" o
LEFT JOIN "user" u ON o.waiter_id = u.id
WHERE o.status = 'processing'
ORDER BY o.created_at ASC
LIMIT $2 OFFSET $1
`

type ListProcessingOrdersParams struct {
	Offset int32 `db:"offset" json:"offset"`
	Limit  int32 `db:"limit" json:"limit"`
}

type ListProcessingOrdersRow struct {
	ID          int32      `db:"id" json:"id"`
	WaiterID    *int32     `db:"waiter_id" json:"waiter_id"`
	Status      string     `db:"status" json:"status"`
	TableNumber string     `db:"table_number" json:"table_number"`
	Note        *string    `db:"note" json:"note"`
	TotalPrice  float32    `db:"total_price" json:"total_price"`
	CreatedAt   time.Time  `db:"created_at" json:"created_at"`
	DeliveredAt *time.Time `db:"delivered_at" json:"delivered_at"`
	UpdatedAt   time.Time  `db:"updated_at" json:"updated_at"`
	WaiterName  *string    `db:"waiter_name" json:"waiter_name"`
}

func (q *Queries) ListProcessingOrders(ctx context.Context, arg ListProcessingOrdersParams) ([]ListProcessingOrdersRow, error) {
	rows, err := q.db.Query(ctx, listProcessingOrders, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProcessingOrdersRow{}
	for rows.Next() {
		var i ListProcessingOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.WaiterID,
			&i.Status,
			&i.TableNumber,
			&i.Note,
			&i.TotalPrice,
			&i.CreatedAt,
			&i.DeliveredAt,
			&i.UpdatedAt,
			&i.WaiterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadyOrders = `-- name: ListReadyOrders :many
SELECT o.id, o.waiter_id, o.status, o.table_number, o.note, o.total_price, o.created_at, o.delivered_at, o.updated_at, u.name AS waiter_name
FROM "order" o
LEFT JOIN "user" u ON o.waiter_id = u.id
WHERE o.status = 'ready'
ORDER BY o.created_at ASC
LIMIT $2 OFFSET $1
`

type ListReadyOrdersParams struct {
	Offset int32 `db:"offset" json:"offset"`
	Limit  int32 `db:"limit" json:"limit"`
}

type ListReadyOrdersRow struct {
	ID          int32      `db:"id" json:"id"`
	WaiterID    *int32     `db:"waiter_id" json:"waiter_id"`
	Status      string     `db:"status" json:"status"`
	TableNumber string     `db:"table_number" json:"table_number"`
	Note        *string    `db:"note" json:"note"`
	TotalPrice  float32    `db:"total_price" json:"total_price"`
	CreatedAt   time.Time  `db:"created_at" json:"created_at"`
	DeliveredAt *time.Time `db:"delivered_at" json:"delivered_at"`
	UpdatedAt   time.Time  `db:"updated_at" json:"updated_at"`
	WaiterName  *string    `db:"waiter_name" json:"waiter_name"`
}

func (q *Queries) ListReadyOrders(ctx context.Context, arg ListReadyOrdersParams) ([]ListReadyOrdersRow, error) {
	rows, err := q.db.Query(ctx, listReadyOrders, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReadyOrdersRow{}
	for rows.Next() {
		var i ListReadyOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.WaiterID,
			&i.Status,
			&i.TableNumber,
			&i.Note,
			&i.TotalPrice,
			&i.CreatedAt,
			&i.DeliveredAt,
			&i.UpdatedAt,
			&i.WaiterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrder = `-- name: UpdateOrder :one
UPDATE "order"
SET
    note = COALESCE($2, note),
    status = COALESCE($3, status),
    waiter_id = COALESCE($4, waiter_id),
    total_price = COALESCE($5, total_price),
    table_number = COALESCE($6, table_number),
    updated_at = NOW()
WHERE id = $1
RETURNING id, waiter_id, status, table_number, note, total_price, created_at, delivered_at, updated_at
`

type UpdateOrderParams struct {
	ID          int32    `db:"id" json:"id"`
	Note        *string  `db:"note" json:"note"`
	Status      *string  `db:"status" json:"status"`
	WaiterID    *int32   `db:"waiter_id" json:"waiter_id"`
	TotalPrice  *float32 `db:"total_price" json:"total_price"`
	TableNumber *string  `db:"table_number" json:"table_number"`
}

func (q *Queries) UpdateOrder(ctx context.Context, arg UpdateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrder,
		arg.ID,
		arg.Note,
		arg.Status,
		arg.WaiterID,
		arg.TotalPrice,
		arg.TableNumber,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.WaiterID,
		&i.Status,
		&i.TableNumber,
		&i.Note,
		&i.TotalPrice,
		&i.CreatedAt,
		&i.DeliveredAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrderItemQuantity = `-- name: UpdateOrderItemQuantity :one
UPDATE order_item
SET quantity = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, order_id, menu_item_id, quantity, price, category, created_at, updated_at
`

type UpdateOrderItemQuantityParams struct {
	ID       int32 `db:"id" json:"id"`
	Quantity int32 `db:"quantity" json:"quantity"`
}

func (q *Queries) UpdateOrderItemQuantity(ctx context.Context, arg UpdateOrderItemQuantityParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, updateOrderItemQuantity, arg.ID, arg.Quantity)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.MenuItemID,
		&i.Quantity,
		&i.Price,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE "order"
SET status = $2,
    updated_at = NOW(),
    delivered_at = Now()
WHERE id = $1
RETURNING id, waiter_id, status, table_number, note, total_price, created_at, delivered_at, updated_at
`

type UpdateOrderStatusParams struct {
	ID     int32  `db:"id" json:"id"`
	Status string `db:"status" json:"status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.ID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.WaiterID,
		&i.Status,
		&i.TableNumber,
		&i.Note,
		&i.TotalPrice,
		&i.CreatedAt,
		&i.DeliveredAt,
		&i.UpdatedAt,
	)
	return i, err
}
