// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: order.sql

package repository

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const addOrderItem = `-- name: AddOrderItem :one
INSERT INTO order_item (order_id, menu_item_id, quantity)
VALUES ($1, $2, $3)
RETURNING id, order_id, menu_item_id, quantity, created_at, updated_at
`

type AddOrderItemParams struct {
	OrderID    int32 `db:"order_id" json:"order_id"`
	MenuItemID int32 `db:"menu_item_id" json:"menu_item_id"`
	Quantity   int32 `db:"quantity" json:"quantity"`
}

func (q *Queries) AddOrderItem(ctx context.Context, arg AddOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, addOrderItem, arg.OrderID, arg.MenuItemID, arg.Quantity)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.MenuItemID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMenuItem = `-- name: CreateMenuItem :one
INSERT INTO menu_item (name, description, price, status, picture, ingredients)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, description, price, picture, status, ingredients, created_at, updated_at
`

type CreateMenuItemParams struct {
	Name        string   `db:"name" json:"name"`
	Description *string  `db:"description" json:"description"`
	Price       float64  `db:"price" json:"price"`
	Status      bool     `db:"status" json:"status"`
	Picture     string   `db:"picture" json:"picture"`
	Ingredients []string `db:"ingredients" json:"ingredients"`
}

func (q *Queries) CreateMenuItem(ctx context.Context, arg CreateMenuItemParams) (MenuItem, error) {
	row := q.db.QueryRow(ctx, createMenuItem,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Status,
		arg.Picture,
		arg.Ingredients,
	)
	var i MenuItem
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Picture,
		&i.Status,
		&i.Ingredients,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO "order" (waiter_id, status, table_number)
VALUES ($1, $2, $3)
RETURNING id, waiter_id, status, table_number, created_at, updated_at
`

type CreateOrderParams struct {
	WaiterID    *int32  `db:"waiter_id" json:"waiter_id"`
	Status      string  `db:"status" json:"status"`
	TableNumber *string `db:"table_number" json:"table_number"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder, arg.WaiterID, arg.Status, arg.TableNumber)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.WaiterID,
		&i.Status,
		&i.TableNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMenuItem = `-- name: DeleteMenuItem :exec
DELETE FROM menu_item WHERE id = $1
`

func (q *Queries) DeleteMenuItem(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteMenuItem, id)
	return err
}

const deleteOrder = `-- name: DeleteOrder :exec
DELETE FROM "order" WHERE id = $1
`

func (q *Queries) DeleteOrder(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteOrder, id)
	return err
}

const deleteOrderItem = `-- name: DeleteOrderItem :exec
DELETE FROM order_item WHERE id = $1
`

func (q *Queries) DeleteOrderItem(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteOrderItem, id)
	return err
}

const getMenuItem = `-- name: GetMenuItem :one
SELECT id, name, description, price, picture, status, ingredients, created_at, updated_at FROM menu_item WHERE id = $1
`

func (q *Queries) GetMenuItem(ctx context.Context, id int32) (MenuItem, error) {
	row := q.db.QueryRow(ctx, getMenuItem, id)
	var i MenuItem
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Picture,
		&i.Status,
		&i.Ingredients,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrder = `-- name: GetOrder :one
SELECT o.id, o.waiter_id, o.status, o.table_number, o.created_at, o.updated_at, u.name AS waiter_name
FROM "order" o
LEFT JOIN "user" u ON o.waiter_id = u.id
WHERE o.id = $1
`

type GetOrderRow struct {
	ID          int32     `db:"id" json:"id"`
	WaiterID    *int32    `db:"waiter_id" json:"waiter_id"`
	Status      string    `db:"status" json:"status"`
	TableNumber *string   `db:"table_number" json:"table_number"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time `db:"updated_at" json:"updated_at"`
	WaiterName  *string   `db:"waiter_name" json:"waiter_name"`
}

func (q *Queries) GetOrder(ctx context.Context, id int32) (GetOrderRow, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i GetOrderRow
	err := row.Scan(
		&i.ID,
		&i.WaiterID,
		&i.Status,
		&i.TableNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WaiterName,
	)
	return i, err
}

const getOrderItems = `-- name: GetOrderItems :many
SELECT oi.id, oi.order_id, oi.menu_item_id, oi.quantity, oi.created_at, oi.updated_at, mi.name, mi.price
FROM order_item oi
JOIN menu_item mi ON oi.menu_item_id = mi.id
WHERE oi.order_id = $1
ORDER BY oi.created_at ASC
`

type GetOrderItemsRow struct {
	ID         int32     `db:"id" json:"id"`
	OrderID    int32     `db:"order_id" json:"order_id"`
	MenuItemID int32     `db:"menu_item_id" json:"menu_item_id"`
	Quantity   int32     `db:"quantity" json:"quantity"`
	CreatedAt  time.Time `db:"created_at" json:"created_at"`
	UpdatedAt  time.Time `db:"updated_at" json:"updated_at"`
	Name       string    `db:"name" json:"name"`
	Price      float64   `db:"price" json:"price"`
}

func (q *Queries) GetOrderItems(ctx context.Context, orderID int32) ([]GetOrderItemsRow, error) {
	rows, err := q.db.Query(ctx, getOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOrderItemsRow{}
	for rows.Next() {
		var i GetOrderItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.MenuItemID,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderWithItems = `-- name: GetOrderWithItems :many
SELECT
    o.id AS order_id,
    o.waiter_id,
    u.name AS waiter_name,
    o.status,
    o.table_number,
    o.created_at AS order_created_at,
    oi.id AS order_item_id,
    oi.quantity,
    mi.id AS menu_item_id,
    mi.name AS menu_item_name,
    mi.price AS menu_item_price
FROM "order" o
LEFT JOIN order_item oi ON o.id = oi.order_id
LEFT JOIN menu_item mi ON oi.menu_item_id = mi.id
LEFT JOIN "user" u ON o.waiter_id = u.id
WHERE o.id = $1
ORDER BY oi.created_at ASC
`

type GetOrderWithItemsRow struct {
	OrderID        int32       `db:"order_id" json:"order_id"`
	WaiterID       *int32      `db:"waiter_id" json:"waiter_id"`
	WaiterName     *string     `db:"waiter_name" json:"waiter_name"`
	Status         string      `db:"status" json:"status"`
	TableNumber    *string     `db:"table_number" json:"table_number"`
	OrderCreatedAt time.Time   `db:"order_created_at" json:"order_created_at"`
	OrderItemID    pgtype.Int4 `db:"order_item_id" json:"order_item_id"`
	Quantity       *int32      `db:"quantity" json:"quantity"`
	MenuItemID     pgtype.Int4 `db:"menu_item_id" json:"menu_item_id"`
	MenuItemName   *string     `db:"menu_item_name" json:"menu_item_name"`
	MenuItemPrice  *float64    `db:"menu_item_price" json:"menu_item_price"`
}

func (q *Queries) GetOrderWithItems(ctx context.Context, id int32) ([]GetOrderWithItemsRow, error) {
	rows, err := q.db.Query(ctx, getOrderWithItems, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOrderWithItemsRow{}
	for rows.Next() {
		var i GetOrderWithItemsRow
		if err := rows.Scan(
			&i.OrderID,
			&i.WaiterID,
			&i.WaiterName,
			&i.Status,
			&i.TableNumber,
			&i.OrderCreatedAt,
			&i.OrderItemID,
			&i.Quantity,
			&i.MenuItemID,
			&i.MenuItemName,
			&i.MenuItemPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMenuItems = `-- name: ListMenuItems :many
SELECT id, name, description, price, picture, status, ingredients, created_at, updated_at FROM menu_item ORDER BY created_at DESC
`

func (q *Queries) ListMenuItems(ctx context.Context) ([]MenuItem, error) {
	rows, err := q.db.Query(ctx, listMenuItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MenuItem{}
	for rows.Next() {
		var i MenuItem
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Picture,
			&i.Status,
			&i.Ingredients,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrders = `-- name: ListOrders :many
SELECT id, waiter_id, status, table_number, created_at, updated_at FROM "order" ORDER BY created_at DESC
`

func (q *Queries) ListOrders(ctx context.Context) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.WaiterID,
			&i.Status,
			&i.TableNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMenuItem = `-- name: UpdateMenuItem :one
UPDATE menu_item
SET
    name = COALESCE($2, name),
    price = COALESCE($3, price),
    status = COALESCE($4, status),
    picture = COALESCE($5, picture),
    description = COALESCE($6, description),
    ingredients = COALESCE($7, ingredients),
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, description, price, picture, status, ingredients, created_at, updated_at
`

type UpdateMenuItemParams struct {
	ID          int32    `db:"id" json:"id"`
	Name        *string  `db:"name" json:"name"`
	Price       *float64 `db:"price" json:"price"`
	Status      *bool    `db:"status" json:"status"`
	Picture     *string  `db:"picture" json:"picture"`
	Description *string  `db:"description" json:"description"`
	Ingredients []string `db:"ingredients" json:"ingredients"`
}

func (q *Queries) UpdateMenuItem(ctx context.Context, arg UpdateMenuItemParams) (MenuItem, error) {
	row := q.db.QueryRow(ctx, updateMenuItem,
		arg.ID,
		arg.Name,
		arg.Price,
		arg.Status,
		arg.Picture,
		arg.Description,
		arg.Ingredients,
	)
	var i MenuItem
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Picture,
		&i.Status,
		&i.Ingredients,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrderItemQuantity = `-- name: UpdateOrderItemQuantity :one
UPDATE order_item
SET quantity = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, order_id, menu_item_id, quantity, created_at, updated_at
`

type UpdateOrderItemQuantityParams struct {
	ID       int32 `db:"id" json:"id"`
	Quantity int32 `db:"quantity" json:"quantity"`
}

func (q *Queries) UpdateOrderItemQuantity(ctx context.Context, arg UpdateOrderItemQuantityParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, updateOrderItemQuantity, arg.ID, arg.Quantity)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.MenuItemID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE "order"
SET status = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, waiter_id, status, table_number, created_at, updated_at
`

type UpdateOrderStatusParams struct {
	ID     int32  `db:"id" json:"id"`
	Status string `db:"status" json:"status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.ID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.WaiterID,
		&i.Status,
		&i.TableNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
