// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: prep-time.sql

package repository

import (
	"context"
)

const avgPreparationTimeDaily = `-- name: AvgPreparationTimeDaily :one
SELECT COALESCE(AVG(EXTRACT(EPOCH FROM (delivered_at - created_at))), 0) AS avg_prep_seconds
FROM "order"
WHERE status = 'delivered'
AND DATE(created_at) = CURRENT_DATE
`

func (q *Queries) AvgPreparationTimeDaily(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRow(ctx, avgPreparationTimeDaily)
	var avg_prep_seconds interface{}
	err := row.Scan(&avg_prep_seconds)
	return avg_prep_seconds, err
}

const avgPreparationTimeMonthly = `-- name: AvgPreparationTimeMonthly :one
SELECT COALESCE(AVG(EXTRACT(EPOCH FROM (delivered_at - created_at))), 0) AS avg_prep_seconds
FROM "order"
WHERE status = 'delivered'
AND DATE_TRUNC('month', created_at) = DATE_TRUNC('month', CURRENT_DATE)
`

func (q *Queries) AvgPreparationTimeMonthly(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRow(ctx, avgPreparationTimeMonthly)
	var avg_prep_seconds interface{}
	err := row.Scan(&avg_prep_seconds)
	return avg_prep_seconds, err
}

const avgPreparationTimeWeekly = `-- name: AvgPreparationTimeWeekly :one
SELECT COALESCE(AVG(EXTRACT(EPOCH FROM (delivered_at - created_at))), 0) AS avg_prep_seconds
FROM "order"
WHERE status = 'delivered'
AND DATE_TRUNC('week', created_at) = DATE_TRUNC('week', CURRENT_DATE)
`

func (q *Queries) AvgPreparationTimeWeekly(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRow(ctx, avgPreparationTimeWeekly)
	var avg_prep_seconds interface{}
	err := row.Scan(&avg_prep_seconds)
	return avg_prep_seconds, err
}
