// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"context"
)

type Querier interface {
	AddOrderItem(ctx context.Context, arg AddOrderItemParams) (OrderItem, error)
	AvgPreparationTimeDaily(ctx context.Context) (interface{}, error)
	AvgPreparationTimeMonthly(ctx context.Context) (interface{}, error)
	AvgPreparationTimeWeekly(ctx context.Context) (interface{}, error)
	BlockAccount(ctx context.Context, userID int32) error
	ClearOrderItems(ctx context.Context, orderID int32) error
	CountActiveOrders(ctx context.Context) (int64, error)
	CountCancelledOrders(ctx context.Context) (int64, error)
	CountCompletedOrdersDaily(ctx context.Context) (int64, error)
	CountCompletedOrdersMonthly(ctx context.Context) (int64, error)
	CountCompletedOrdersWeekly(ctx context.Context) (int64, error)
	CountDeliveredOrders(ctx context.Context) (int64, error)
	CountListAuditLogs(ctx context.Context) (int64, error)
	CountPendingOrders(ctx context.Context) (int64, error)
	CountProcessingOrders(ctx context.Context) (int64, error)
	CountReadyOrders(ctx context.Context) (int64, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) error
	CreateMenuItem(ctx context.Context, arg CreateMenuItemParams) (MenuItem, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetTokens, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (int32, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredTokens(ctx context.Context) error
	DeleteMenuItem(ctx context.Context, id int32) error
	DeleteOrder(ctx context.Context, id int32) error
	DeleteOrderItem(ctx context.Context, id int32) error
	DeleteRefreshToken(ctx context.Context, token string) error
	DeleteRefreshTokensByUser(ctx context.Context, userID int32) error
	GetAccount(ctx context.Context, userID int32) (Account, error)
	GetAuditLog(ctx context.Context, id int32) (GetAuditLogRow, error)
	GetCompletedOrdersDaily(ctx context.Context) ([]Order, error)
	GetCompletedOrdersMonthly(ctx context.Context) ([]Order, error)
	GetCompletedOrdersWeekly(ctx context.Context) ([]Order, error)
	GetMenuItem(ctx context.Context, id int32) (MenuItem, error)
	GetOrder(ctx context.Context, id int32) (GetOrderRow, error)
	GetOrderItems(ctx context.Context, orderID int32) ([]GetOrderItemsRow, error)
	GetRefreshToken(ctx context.Context, token string) (RefreshTokens, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id int32) (GetUserByIDRow, error)
	GetUserRole(ctx context.Context, id int32) (string, error)
	GetValidPasswordResetToken(ctx context.Context, token string) (PasswordResetTokens, error)
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error
	ListActiveMenuItems(ctx context.Context) ([]MenuItem, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error)
	ListCancelledOrders(ctx context.Context, arg ListCancelledOrdersParams) ([]ListCancelledOrdersRow, error)
	ListDeliveredOrders(ctx context.Context, arg ListDeliveredOrdersParams) ([]ListDeliveredOrdersRow, error)
	ListMenuItems(ctx context.Context) ([]MenuItem, error)
	ListPendingOrders(ctx context.Context, arg ListPendingOrdersParams) ([]ListPendingOrdersRow, error)
	ListProcessingOrders(ctx context.Context, arg ListProcessingOrdersParams) ([]ListProcessingOrdersRow, error)
	ListReadyOrders(ctx context.Context, arg ListReadyOrdersParams) ([]ListReadyOrdersRow, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
	MarkTokenAsUsed(ctx context.Context, id int32) error
	SoftDeleteUser(ctx context.Context, id int32) error
	UnblockAccount(ctx context.Context, userID int32) error
	UpdateMenuItem(ctx context.Context, arg UpdateMenuItemParams) (MenuItem, error)
	UpdateOrder(ctx context.Context, arg UpdateOrderParams) (Order, error)
	UpdateOrderItemQuantity(ctx context.Context, arg UpdateOrderItemQuantityParams) (OrderItem, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
	UpdateUserInfo(ctx context.Context, arg UpdateUserInfoParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
