// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"context"
)

type Querier interface {
	AddOrderItem(ctx context.Context, arg AddOrderItemParams) (OrderItem, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) error
	CreateMenuItem(ctx context.Context, arg CreateMenuItemParams) (MenuItem, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetTokens, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (int32, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredTokens(ctx context.Context) error
	DeleteMenuItem(ctx context.Context, id int32) error
	DeleteOrder(ctx context.Context, id int32) error
	DeleteOrderItem(ctx context.Context, id int32) error
	DeleteRefreshToken(ctx context.Context, token string) error
	DeleteRefreshTokensByUser(ctx context.Context, userID int32) error
	GetAccount(ctx context.Context, userID int32) (Account, error)
	GetMenuItem(ctx context.Context, id int32) (MenuItem, error)
	GetOrder(ctx context.Context, id int32) (GetOrderRow, error)
	GetOrderItems(ctx context.Context, orderID int32) ([]GetOrderItemsRow, error)
	GetOrderWithItems(ctx context.Context, id int32) ([]GetOrderWithItemsRow, error)
	GetRefreshToken(ctx context.Context, token string) (RefreshTokens, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	GetUserRole(ctx context.Context, id int32) (string, error)
	GetValidPasswordResetToken(ctx context.Context, token string) (PasswordResetTokens, error)
	ListMenuItems(ctx context.Context) ([]MenuItem, error)
	ListOrders(ctx context.Context) ([]Order, error)
	ListUsers(ctx context.Context) ([]User, error)
	MarkTokenAsUsed(ctx context.Context, id int32) error
	SoftDeleteUser(ctx context.Context, id int32) error
	UpdateMenuItem(ctx context.Context, arg UpdateMenuItemParams) (MenuItem, error)
	UpdateOrderItemQuantity(ctx context.Context, arg UpdateOrderItemQuantityParams) (OrderItem, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
	UpdateUserInfo(ctx context.Context, arg UpdateUserInfoParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error
}

var _ Querier = (*Queries)(nil)
