// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: reset_password.sql

package repository

import (
	"context"
	"time"
)

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one
INSERT INTO password_reset_tokens (user_id, token, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token, expires_at, created_at, used_at
`

type CreatePasswordResetTokenParams struct {
	UserID    int32     `db:"user_id" json:"user_id"`
	Token     string    `db:"token" json:"token"`
	ExpiresAt time.Time `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetTokens, error) {
	row := q.db.QueryRow(ctx, createPasswordResetToken, arg.UserID, arg.Token, arg.ExpiresAt)
	var i PasswordResetTokens
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UsedAt,
	)
	return i, err
}

const deleteExpiredTokens = `-- name: DeleteExpiredTokens :exec
DELETE FROM password_reset_tokens
WHERE expires_at <= NOW()
    OR used_at IS NOT NULL
`

func (q *Queries) DeleteExpiredTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredTokens)
	return err
}

const getValidPasswordResetToken = `-- name: GetValidPasswordResetToken :one
SELECT id, user_id, token, expires_at, created_at, used_at
FROM password_reset_tokens
WHERE token = $1
    AND expires_at > NOW()
    AND used_at IS NULL
LIMIT 1
`

func (q *Queries) GetValidPasswordResetToken(ctx context.Context, token string) (PasswordResetTokens, error) {
	row := q.db.QueryRow(ctx, getValidPasswordResetToken, token)
	var i PasswordResetTokens
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UsedAt,
	)
	return i, err
}

const markTokenAsUsed = `-- name: MarkTokenAsUsed :exec
UPDATE password_reset_tokens
SET used_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkTokenAsUsed(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, markTokenAsUsed, id)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE account
SET password_hash = $1
WHERE user_id = $2
`

type UpdateUserPasswordParams struct {
	PasswordHash string `db:"password_hash" json:"password_hash"`
	UserID       int32  `db:"user_id" json:"user_id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.PasswordHash, arg.UserID)
	return err
}
