// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: revenue.sql

package repository

import (
	"context"
	"time"
)

const ordersAndRevenueDaily = `-- name: OrdersAndRevenueDaily :many
SELECT date_trunc('day', oi.created_at)::timestamptz AS period,
       COUNT(DISTINCT oi.order_id) AS total_orders,
       SUM(oi.price * oi.quantity)::double precision AS total_revenue
FROM order_item oi
GROUP BY period
ORDER BY period
`

type OrdersAndRevenueDailyRow struct {
	Period       time.Time `db:"period" json:"period"`
	TotalOrders  int64     `db:"total_orders" json:"total_orders"`
	TotalRevenue float32   `db:"total_revenue" json:"total_revenue"`
}

func (q *Queries) OrdersAndRevenueDaily(ctx context.Context) ([]OrdersAndRevenueDailyRow, error) {
	rows, err := q.db.Query(ctx, ordersAndRevenueDaily)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrdersAndRevenueDailyRow{}
	for rows.Next() {
		var i OrdersAndRevenueDailyRow
		if err := rows.Scan(&i.Period, &i.TotalOrders, &i.TotalRevenue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ordersAndRevenueMonthly = `-- name: OrdersAndRevenueMonthly :many
SELECT date_trunc('month', oi.created_at)::timestamptz AS period,
       COUNT(DISTINCT oi.order_id) AS total_orders,
       SUM(oi.price * oi.quantity)::double precision AS total_revenue
FROM order_item oi
GROUP BY period
ORDER BY period
`

type OrdersAndRevenueMonthlyRow struct {
	Period       time.Time `db:"period" json:"period"`
	TotalOrders  int64     `db:"total_orders" json:"total_orders"`
	TotalRevenue float32   `db:"total_revenue" json:"total_revenue"`
}

func (q *Queries) OrdersAndRevenueMonthly(ctx context.Context) ([]OrdersAndRevenueMonthlyRow, error) {
	rows, err := q.db.Query(ctx, ordersAndRevenueMonthly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrdersAndRevenueMonthlyRow{}
	for rows.Next() {
		var i OrdersAndRevenueMonthlyRow
		if err := rows.Scan(&i.Period, &i.TotalOrders, &i.TotalRevenue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ordersAndRevenueWeekly = `-- name: OrdersAndRevenueWeekly :many
SELECT date_trunc('week', oi.created_at)::timestamptz AS period,
       COUNT(DISTINCT oi.order_id) AS total_orders,
       SUM(oi.price * oi.quantity)::double precision AS total_revenue
FROM order_item oi
GROUP BY period
ORDER BY period
`

type OrdersAndRevenueWeeklyRow struct {
	Period       time.Time `db:"period" json:"period"`
	TotalOrders  int64     `db:"total_orders" json:"total_orders"`
	TotalRevenue float32   `db:"total_revenue" json:"total_revenue"`
}

func (q *Queries) OrdersAndRevenueWeekly(ctx context.Context) ([]OrdersAndRevenueWeeklyRow, error) {
	rows, err := q.db.Query(ctx, ordersAndRevenueWeekly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrdersAndRevenueWeeklyRow{}
	for rows.Next() {
		var i OrdersAndRevenueWeeklyRow
		if err := rows.Scan(&i.Period, &i.TotalOrders, &i.TotalRevenue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const totalRevenue = `-- name: TotalRevenue :one
SELECT COALESCE(SUM(oi.price * oi.quantity), 0) AS total_revenue
FROM order_item oi
`

func (q *Queries) TotalRevenue(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRow(ctx, totalRevenue)
	var total_revenue interface{}
	err := row.Scan(&total_revenue)
	return total_revenue, err
}
