// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package repository

import (
	"context"
)

const createAccount = `-- name: CreateAccount :exec
INSERT INTO account (user_id, password_hash)
VALUES ($1, $2)
`

type CreateAccountParams struct {
	UserID       int32  `db:"user_id" json:"user_id"`
	PasswordHash string `db:"password_hash" json:"password_hash"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) error {
	_, err := q.db.Exec(ctx, createAccount, arg.UserID, arg.PasswordHash)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO "user" (name, email, phone, role, picture)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, email, phone, role, picture, created_at, deleted_at
`

type CreateUserParams struct {
	Name    string  `db:"name" json:"name"`
	Email   string  `db:"email" json:"email"`
	Phone   string  `db:"phone" json:"phone"`
	Role    string  `db:"role" json:"role"`
	Picture *string `db:"picture" json:"picture"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Role,
		arg.Picture,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Role,
		&i.Picture,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, password_hash, user_id, created_at, deleted_at FROM account
WHERE account.user_id = $1
`

func (q *Queries) GetAccount(ctx context.Context, userID int32) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, userID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.PasswordHash,
		&i.UserID,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, phone, role, picture, created_at, deleted_at
FROM "user"
WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Role,
		&i.Picture,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, phone, role, picture, created_at, deleted_at
FROM "user"
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Role,
		&i.Picture,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserRole = `-- name: GetUserRole :one
SELECT role FROM "user" WHERE id = $1
`

func (q *Queries) GetUserRole(ctx context.Context, id int32) (string, error) {
	row := q.db.QueryRow(ctx, getUserRole, id)
	var role string
	err := row.Scan(&role)
	return role, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email, phone, role, picture, created_at, deleted_at
FROM "user"
WHERE deleted_at IS NULL
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.Role,
			&i.Picture,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE "user"
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const updateUserInfo = `-- name: UpdateUserInfo :one
UPDATE "user"
SET name = $2, picture = $5, email = $3, phone = $4
WHERE id = $1
RETURNING id, name, email, phone, role, picture, created_at, deleted_at
`

type UpdateUserInfoParams struct {
	ID      int32   `db:"id" json:"id"`
	Name    string  `db:"name" json:"name"`
	Email   string  `db:"email" json:"email"`
	Phone   string  `db:"phone" json:"phone"`
	Picture *string `db:"picture" json:"picture"`
}

func (q *Queries) UpdateUserInfo(ctx context.Context, arg UpdateUserInfoParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserInfo,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Picture,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Role,
		&i.Picture,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE "user"
SET role = $2
WHERE id = $1
`

type UpdateUserRoleParams struct {
	ID   int32  `db:"id" json:"id"`
	Role string `db:"role" json:"role"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.Exec(ctx, updateUserRole, arg.ID, arg.Role)
	return err
}
