// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package repository

import (
	"context"
	"time"
)

const createUser = `-- name: CreateUser :one
INSERT INTO "user" (name, email, phone, role, picture)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, email, phone, role, picture, created_at, deleted_at
`

type CreateUserParams struct {
	Name    string  `db:"name" json:"name"`
	Email   string  `db:"email" json:"email"`
	Phone   string  `db:"phone" json:"phone"`
	Role    string  `db:"role" json:"role"`
	Picture *string `db:"picture" json:"picture"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Role,
		arg.Picture,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Role,
		&i.Picture,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT u.id, u.name, u.email, u.phone, u.role, u.picture, u.created_at, u.deleted_at, a.blocked AS blocked
FROM "user" u
LEFT JOIN account a ON u.id = a.user_id
WHERE u.email = $1 AND u.deleted_at IS NULL
`

type GetUserByEmailRow struct {
	ID        int32      `db:"id" json:"id"`
	Name      string     `db:"name" json:"name"`
	Email     string     `db:"email" json:"email"`
	Phone     string     `db:"phone" json:"phone"`
	Role      string     `db:"role" json:"role"`
	Picture   *string    `db:"picture" json:"picture"`
	CreatedAt time.Time  `db:"created_at" json:"created_at"`
	DeletedAt *time.Time `db:"deleted_at" json:"deleted_at"`
	Blocked   *bool      `db:"blocked" json:"blocked"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Role,
		&i.Picture,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.Blocked,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT u.id, u.name, u.email, u.phone, u.role, u.picture, u.created_at, u.deleted_at, a.blocked AS blocked
FROM "user" u
LEFT JOIN account a ON u.id = a.user_id
WHERE u.id = $1 AND u.deleted_at IS NULL
`

type GetUserByIDRow struct {
	ID        int32      `db:"id" json:"id"`
	Name      string     `db:"name" json:"name"`
	Email     string     `db:"email" json:"email"`
	Phone     string     `db:"phone" json:"phone"`
	Role      string     `db:"role" json:"role"`
	Picture   *string    `db:"picture" json:"picture"`
	CreatedAt time.Time  `db:"created_at" json:"created_at"`
	DeletedAt *time.Time `db:"deleted_at" json:"deleted_at"`
	Blocked   *bool      `db:"blocked" json:"blocked"`
}

func (q *Queries) GetUserByID(ctx context.Context, id int32) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Role,
		&i.Picture,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.Blocked,
	)
	return i, err
}

const getUserRole = `-- name: GetUserRole :one
SELECT role FROM "user" WHERE id = $1
`

func (q *Queries) GetUserRole(ctx context.Context, id int32) (string, error) {
	row := q.db.QueryRow(ctx, getUserRole, id)
	var role string
	err := row.Scan(&role)
	return role, err
}

const listUsers = `-- name: ListUsers :many
SELECT u.id, u.name, u.email, u.phone, u.role, u.picture, u.created_at, u.deleted_at, a.blocked AS blocked
FROM "user" u
LEFT JOIN account a ON u.id = a.user_id
WHERE u.deleted_at IS NULL
ORDER BY u.name ASC
`

type ListUsersRow struct {
	ID        int32      `db:"id" json:"id"`
	Name      string     `db:"name" json:"name"`
	Email     string     `db:"email" json:"email"`
	Phone     string     `db:"phone" json:"phone"`
	Role      string     `db:"role" json:"role"`
	Picture   *string    `db:"picture" json:"picture"`
	CreatedAt time.Time  `db:"created_at" json:"created_at"`
	DeletedAt *time.Time `db:"deleted_at" json:"deleted_at"`
	Blocked   *bool      `db:"blocked" json:"blocked"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.Role,
			&i.Picture,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.Blocked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE "user"
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const topActiveUsers = `-- name: TopActiveUsers :many
SELECT u.id,
       u.name,
       u.role,
       u.picture,
       COUNT(*) AS total_actions
FROM activity_log al
JOIN "user" u ON u.id = al.actor_id
GROUP BY u.id, u.name, u.role
ORDER BY total_actions DESC
LIMIT 10
`

type TopActiveUsersRow struct {
	ID           int32   `db:"id" json:"id"`
	Name         string  `db:"name" json:"name"`
	Role         string  `db:"role" json:"role"`
	Picture      *string `db:"picture" json:"picture"`
	TotalActions int64   `db:"total_actions" json:"total_actions"`
}

func (q *Queries) TopActiveUsers(ctx context.Context) ([]TopActiveUsersRow, error) {
	rows, err := q.db.Query(ctx, topActiveUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopActiveUsersRow{}
	for rows.Next() {
		var i TopActiveUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.Picture,
			&i.TotalActions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserInfo = `-- name: UpdateUserInfo :one
UPDATE "user"
SET
    name = COALESCE($2, name),
    email = COALESCE($3, email),
    phone = COALESCE($4, phone),
    role = COALESCE($5, role),
    picture = COALESCE($6, picture)
WHERE id = $1
RETURNING id, name, email, phone, role, picture, created_at, deleted_at
`

type UpdateUserInfoParams struct {
	ID      int32   `db:"id" json:"id"`
	Name    *string `db:"name" json:"name"`
	Email   *string `db:"email" json:"email"`
	Phone   *string `db:"phone" json:"phone"`
	Role    *string `db:"role" json:"role"`
	Picture *string `db:"picture" json:"picture"`
}

func (q *Queries) UpdateUserInfo(ctx context.Context, arg UpdateUserInfoParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserInfo,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Role,
		arg.Picture,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Role,
		&i.Picture,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
