// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: waiter.sql

package repository

import (
	"context"
	"time"
)

const waiterPerformanceDaily = `-- name: WaiterPerformanceDaily :many
SELECT u.id,
       u.name,
       u.picture,
       date_trunc('day', al.ts)::timestamptz AS period,
       COUNT(*) FILTER (WHERE al.action_type = 'CREATE_ORDER') AS created_orders,
       COUNT(*) FILTER (WHERE al.action_type = 'UPDATE_ORDER') AS updated_orders,
       COUNT(*) FILTER (WHERE al.action_type = 'UPDATE_ORDER_STATUS') AS status_updates,
       COUNT(*) AS total_actions
FROM activity_log al
JOIN "user" u ON u.id = al.actor_id
WHERE u.role = 'waiter'
  AND al.action_type IN ('CREATE_ORDER', 'UPDATE_ORDER', 'UPDATE_ORDER_STATUS')
GROUP BY u.id, u.name, period
ORDER BY period, total_actions DESC
`

type WaiterPerformanceDailyRow struct {
	ID            int32     `db:"id" json:"id"`
	Name          string    `db:"name" json:"name"`
	Picture       *string   `db:"picture" json:"picture"`
	Period        time.Time `db:"period" json:"period"`
	CreatedOrders int64     `db:"created_orders" json:"created_orders"`
	UpdatedOrders int64     `db:"updated_orders" json:"updated_orders"`
	StatusUpdates int64     `db:"status_updates" json:"status_updates"`
	TotalActions  int64     `db:"total_actions" json:"total_actions"`
}

func (q *Queries) WaiterPerformanceDaily(ctx context.Context) ([]WaiterPerformanceDailyRow, error) {
	rows, err := q.db.Query(ctx, waiterPerformanceDaily)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WaiterPerformanceDailyRow{}
	for rows.Next() {
		var i WaiterPerformanceDailyRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Picture,
			&i.Period,
			&i.CreatedOrders,
			&i.UpdatedOrders,
			&i.StatusUpdates,
			&i.TotalActions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const waiterPerformanceMonthly = `-- name: WaiterPerformanceMonthly :many
SELECT u.id,
       u.name,
       u.picture,
       date_trunc('month', al.ts)::timestamptz AS period,
       COUNT(*) FILTER (WHERE al.action_type = 'CREATE_ORDER') AS created_orders,
       COUNT(*) FILTER (WHERE al.action_type = 'UPDATE_ORDER') AS updated_orders,
       COUNT(*) FILTER (WHERE al.action_type = 'UPDATE_ORDER_STATUS') AS status_updates,
       COUNT(*) AS total_actions
FROM activity_log al
JOIN "user" u ON u.id = al.actor_id
WHERE u.role = 'waiter'
  AND al.action_type IN ('CREATE_ORDER', 'UPDATE_ORDER', 'UPDATE_ORDER_STATUS')
GROUP BY u.id, u.name, period
ORDER BY period, total_actions DESC
`

type WaiterPerformanceMonthlyRow struct {
	ID            int32     `db:"id" json:"id"`
	Name          string    `db:"name" json:"name"`
	Picture       *string   `db:"picture" json:"picture"`
	Period        time.Time `db:"period" json:"period"`
	CreatedOrders int64     `db:"created_orders" json:"created_orders"`
	UpdatedOrders int64     `db:"updated_orders" json:"updated_orders"`
	StatusUpdates int64     `db:"status_updates" json:"status_updates"`
	TotalActions  int64     `db:"total_actions" json:"total_actions"`
}

func (q *Queries) WaiterPerformanceMonthly(ctx context.Context) ([]WaiterPerformanceMonthlyRow, error) {
	rows, err := q.db.Query(ctx, waiterPerformanceMonthly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WaiterPerformanceMonthlyRow{}
	for rows.Next() {
		var i WaiterPerformanceMonthlyRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Picture,
			&i.Period,
			&i.CreatedOrders,
			&i.UpdatedOrders,
			&i.StatusUpdates,
			&i.TotalActions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const waiterPerformanceSummary = `-- name: WaiterPerformanceSummary :many
SELECT u.id,
       u.name,
       u.picture,
       COUNT(*) FILTER (WHERE al.action_type = 'CREATE_ORDER') AS created_orders,
       COUNT(*) FILTER (WHERE al.action_type = 'UPDATE_ORDER') AS updated_orders,
       COUNT(*) FILTER (WHERE al.action_type = 'UPDATE_ORDER_STATUS') AS status_updates,
       COUNT(*) AS total_actions
FROM "user" u
LEFT JOIN activity_log al ON u.id = al.actor_id
  AND al.action_type IN ('CREATE_ORDER', 'UPDATE_ORDER', 'UPDATE_ORDER_STATUS')
WHERE u.role = 'waiter'
GROUP BY u.id, u.name
ORDER BY total_actions DESC
`

type WaiterPerformanceSummaryRow struct {
	ID            int32   `db:"id" json:"id"`
	Name          string  `db:"name" json:"name"`
	Picture       *string `db:"picture" json:"picture"`
	CreatedOrders int64   `db:"created_orders" json:"created_orders"`
	UpdatedOrders int64   `db:"updated_orders" json:"updated_orders"`
	StatusUpdates int64   `db:"status_updates" json:"status_updates"`
	TotalActions  int64   `db:"total_actions" json:"total_actions"`
}

func (q *Queries) WaiterPerformanceSummary(ctx context.Context) ([]WaiterPerformanceSummaryRow, error) {
	rows, err := q.db.Query(ctx, waiterPerformanceSummary)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WaiterPerformanceSummaryRow{}
	for rows.Next() {
		var i WaiterPerformanceSummaryRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Picture,
			&i.CreatedOrders,
			&i.UpdatedOrders,
			&i.StatusUpdates,
			&i.TotalActions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const waiterPerformanceWeekly = `-- name: WaiterPerformanceWeekly :many
SELECT u.id,
       u.name,
       u.picture,
       date_trunc('week', al.ts)::timestamptz AS period,
       COUNT(*) FILTER (WHERE al.action_type = 'CREATE_ORDER') AS created_orders,
       COUNT(*) FILTER (WHERE al.action_type = 'UPDATE_ORDER') AS updated_orders,
       COUNT(*) FILTER (WHERE al.action_type = 'UPDATE_ORDER_STATUS') AS status_updates,
       COUNT(*) AS total_actions
FROM activity_log al
JOIN "user" u ON u.id = al.actor_id
WHERE u.role = 'waiter'
  AND al.action_type IN ('CREATE_ORDER', 'UPDATE_ORDER', 'UPDATE_ORDER_STATUS')
GROUP BY u.id, u.name, period
ORDER BY period, total_actions DESC
`

type WaiterPerformanceWeeklyRow struct {
	ID            int32     `db:"id" json:"id"`
	Name          string    `db:"name" json:"name"`
	Picture       *string   `db:"picture" json:"picture"`
	Period        time.Time `db:"period" json:"period"`
	CreatedOrders int64     `db:"created_orders" json:"created_orders"`
	UpdatedOrders int64     `db:"updated_orders" json:"updated_orders"`
	StatusUpdates int64     `db:"status_updates" json:"status_updates"`
	TotalActions  int64     `db:"total_actions" json:"total_actions"`
}

func (q *Queries) WaiterPerformanceWeekly(ctx context.Context) ([]WaiterPerformanceWeeklyRow, error) {
	rows, err := q.db.Query(ctx, waiterPerformanceWeekly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WaiterPerformanceWeeklyRow{}
	for rows.Next() {
		var i WaiterPerformanceWeeklyRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Picture,
			&i.Period,
			&i.CreatedOrders,
			&i.UpdatedOrders,
			&i.StatusUpdates,
			&i.TotalActions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const waiterSelfPerformanceDaily = `-- name: WaiterSelfPerformanceDaily :many
SELECT date_trunc('day', al.ts)::timestamptz AS period,
       COUNT(*) FILTER (WHERE al.action_type = 'CREATE_ORDER') AS created_orders,
       COUNT(*) FILTER (WHERE al.action_type = 'UPDATE_ORDER') AS updated_orders,
       COUNT(*) FILTER (WHERE al.action_type = 'UPDATE_ORDER_STATUS') AS status_updates,
       COUNT(*) AS total_actions
FROM activity_log al
WHERE al.actor_id = $1
  AND al.action_type IN ('CREATE_ORDER', 'UPDATE_ORDER', 'UPDATE_ORDER_STATUS')
GROUP BY period
ORDER BY period
`

type WaiterSelfPerformanceDailyRow struct {
	Period        time.Time `db:"period" json:"period"`
	CreatedOrders int64     `db:"created_orders" json:"created_orders"`
	UpdatedOrders int64     `db:"updated_orders" json:"updated_orders"`
	StatusUpdates int64     `db:"status_updates" json:"status_updates"`
	TotalActions  int64     `db:"total_actions" json:"total_actions"`
}

func (q *Queries) WaiterSelfPerformanceDaily(ctx context.Context, actorID int32) ([]WaiterSelfPerformanceDailyRow, error) {
	rows, err := q.db.Query(ctx, waiterSelfPerformanceDaily, actorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WaiterSelfPerformanceDailyRow{}
	for rows.Next() {
		var i WaiterSelfPerformanceDailyRow
		if err := rows.Scan(
			&i.Period,
			&i.CreatedOrders,
			&i.UpdatedOrders,
			&i.StatusUpdates,
			&i.TotalActions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const waiterSelfPerformanceMonthly = `-- name: WaiterSelfPerformanceMonthly :many
SELECT date_trunc('month', al.ts)::timestamptz AS period,
       COUNT(*) FILTER (WHERE al.action_type = 'CREATE_ORDER') AS created_orders,
       COUNT(*) FILTER (WHERE al.action_type = 'UPDATE_ORDER') AS updated_orders,
       COUNT(*) FILTER (WHERE al.action_type = 'UPDATE_ORDER_STATUS') AS status_updates,
       COUNT(*) AS total_actions
FROM activity_log al
WHERE al.actor_id = $1
  AND al.action_type IN ('CREATE_ORDER', 'UPDATE_ORDER', 'UPDATE_ORDER_STATUS')
GROUP BY period
ORDER BY period
`

type WaiterSelfPerformanceMonthlyRow struct {
	Period        time.Time `db:"period" json:"period"`
	CreatedOrders int64     `db:"created_orders" json:"created_orders"`
	UpdatedOrders int64     `db:"updated_orders" json:"updated_orders"`
	StatusUpdates int64     `db:"status_updates" json:"status_updates"`
	TotalActions  int64     `db:"total_actions" json:"total_actions"`
}

func (q *Queries) WaiterSelfPerformanceMonthly(ctx context.Context, actorID int32) ([]WaiterSelfPerformanceMonthlyRow, error) {
	rows, err := q.db.Query(ctx, waiterSelfPerformanceMonthly, actorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WaiterSelfPerformanceMonthlyRow{}
	for rows.Next() {
		var i WaiterSelfPerformanceMonthlyRow
		if err := rows.Scan(
			&i.Period,
			&i.CreatedOrders,
			&i.UpdatedOrders,
			&i.StatusUpdates,
			&i.TotalActions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const waiterSelfPerformanceSummary = `-- name: WaiterSelfPerformanceSummary :one
SELECT COUNT(*) FILTER (WHERE al.action_type = 'CREATE_ORDER') AS created_orders,
       COUNT(*) FILTER (WHERE al.action_type = 'UPDATE_ORDER') AS updated_orders,
       COUNT(*) FILTER (WHERE al.action_type = 'UPDATE_ORDER_STATUS') AS status_updates,
       COUNT(*) AS total_actions
FROM activity_log al
WHERE al.actor_id = $1
  AND al.action_type IN ('CREATE_ORDER', 'UPDATE_ORDER', 'UPDATE_ORDER_STATUS')
`

type WaiterSelfPerformanceSummaryRow struct {
	CreatedOrders int64 `db:"created_orders" json:"created_orders"`
	UpdatedOrders int64 `db:"updated_orders" json:"updated_orders"`
	StatusUpdates int64 `db:"status_updates" json:"status_updates"`
	TotalActions  int64 `db:"total_actions" json:"total_actions"`
}

func (q *Queries) WaiterSelfPerformanceSummary(ctx context.Context, actorID int32) (WaiterSelfPerformanceSummaryRow, error) {
	row := q.db.QueryRow(ctx, waiterSelfPerformanceSummary, actorID)
	var i WaiterSelfPerformanceSummaryRow
	err := row.Scan(
		&i.CreatedOrders,
		&i.UpdatedOrders,
		&i.StatusUpdates,
		&i.TotalActions,
	)
	return i, err
}

const waiterSelfPerformanceWeekly = `-- name: WaiterSelfPerformanceWeekly :many
SELECT date_trunc('week', al.ts)::timestamptz AS period,
       COUNT(*) FILTER (WHERE al.action_type = 'CREATE_ORDER') AS created_orders,
       COUNT(*) FILTER (WHERE al.action_type = 'UPDATE_ORDER') AS updated_orders,
       COUNT(*) FILTER (WHERE al.action_type = 'UPDATE_ORDER_STATUS') AS status_updates,
       COUNT(*) AS total_actions
FROM activity_log al
WHERE al.actor_id = $1
  AND al.action_type IN ('CREATE_ORDER', 'UPDATE_ORDER', 'UPDATE_ORDER_STATUS')
GROUP BY period
ORDER BY period
`

type WaiterSelfPerformanceWeeklyRow struct {
	Period        time.Time `db:"period" json:"period"`
	CreatedOrders int64     `db:"created_orders" json:"created_orders"`
	UpdatedOrders int64     `db:"updated_orders" json:"updated_orders"`
	StatusUpdates int64     `db:"status_updates" json:"status_updates"`
	TotalActions  int64     `db:"total_actions" json:"total_actions"`
}

func (q *Queries) WaiterSelfPerformanceWeekly(ctx context.Context, actorID int32) ([]WaiterSelfPerformanceWeeklyRow, error) {
	rows, err := q.db.Query(ctx, waiterSelfPerformanceWeekly, actorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WaiterSelfPerformanceWeeklyRow{}
	for rows.Next() {
		var i WaiterSelfPerformanceWeeklyRow
		if err := rows.Scan(
			&i.Period,
			&i.CreatedOrders,
			&i.UpdatedOrders,
			&i.StatusUpdates,
			&i.TotalActions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
