export const queryKeys = {
  all: () => ['query'],
  me: () => ['query', 'auth', 'me'],
  order: (id: number) => ['query', 'orders', 'one', { id }],
  orderItems: (id: number) => ['query', 'orders', 'items', { id }],
  orders: (page: number, limit: number) => [
    'query',
    'orders',
    { page },
    { limit },
  ],
  completedOrders: (page: number, limit: number) => [
    'query',
    'orders',
    'completed',
    { page },
    { limit },
  ],
  menu: (id: number) => ['query', 'menu', 'one', { id }],
  allmenu: () => ['query', 'menu'],
  user: (id: number) => ['query', 'users', 'one', { id }],
  users: () => ['query', 'users'],
  log: (id: string) => ['query', 'logs', 'one', { id }],
  logs: (page: number, rows: number) => ['query', 'logs', { page }, { rows }],
  analytics: {
    countCompletedOrders: (target: string) => [
      'query',
      'analytics',
      'completed-orders',
      { target },
    ],
    avgPrepTime: (target: string) => [
      'query',
      'analytics',
      'avg-prep-time',
      { target },
    ],
    countActiveOrders: () => ['query', 'analytics', 'active-orders'],
  },
}
