export const queryKeys = {
  all: () => ['query'],
  resident: (id: string) => ['query', 'residents', 'one', { id }],
  idcard: (id: string) => ['query', 'idcard', { id }],
  documents: (id: string) => ['query', 'residents', 'one', { id }, 'documents'],
  payment: (id: string) => ['query', 'residents', 'one', { id }, 'payment'],
  address: (id: string) => ['query', 'residents', 'one', { id }, 'address'],
  residents: (page: number, rows: number, query: string) => [
    'query',
    'residents',
    { page },
    { rows },
    { query },
  ],
  me: () => ['query', 'auth', 'me'],
  cities: (page: number, rows: number, query: string) => [
    'query',
    'cities',
    { page },
    { rows },
    { query },
  ],
  kebeles: (page: number, rows: number, query: string) => [
    'query',
    'kebeles',
    { page },
    { rows },
    { query },
  ],
  subCities: (page: number, rows: number, query: string) => [
    'query',
    'subcities',
    { page },
    { rows },
    { query },
  ],
  city: (id: string) => ['query', 'cities', 'one', { id }],
  kebele: (id: string) => ['query', 'kebeles', 'one', { id }],
  subCity: (id: string) => ['query', 'subcities', 'one', { id }],
  users: () => ['query', 'users'],
  user: (id?: string) => ['query', 'users', 'one', { id }],
  userPermissions: (id?: string) => [
    'query',
    'users',
    'one',
    'permissions',
    { id },
  ],
  roles: (role?: string) => ['query', 'roles', { role }],
  usersByRole: (
    role_slug: string,
    page: number,
    rows: number,
    query: string,
  ) => ['query', 'users', { role_slug }, { page }, { rows }, { query }],
  rolePermission: () => ['query', 'rolePermission'],
  log: (id: string) => ['query', 'logs', 'one', { id }],
  logs: (page: number, rows: number) => ['query', 'logs', { page }, { rows }],
  analytics: (target: string) => ['query', 'analytics', { target }],
}
