export const queryKeys = {
  all: () => ['query'],
  me: () => ['query', 'auth', 'me'],
  order: (id: number) => ['query', 'orders', 'one', { id }],
  orderItems: (id: number) => ['query', 'orders', 'items', { id }],
  orders: (page: number, limit: number, target: string) => [
    'query',
    'orders',
    { page },
    { limit },
    { target },
  ],
  completedOrders: (page: number, limit: number) => [
    'query',
    'orders',
    'completed',
    { page },
    { limit },
  ],
  menu: (id: number) => ['query', 'menu', 'one', { id }],
  allmenu: () => ['query', 'menu'],
  user: (id: number) => ['query', 'users', 'one', { id }],
  users: () => ['query', 'users'],
  log: (id: string) => ['query', 'logs', 'one', { id }],
  logs: (page: number, rows: number) => ['query', 'logs', { page }, { rows }],
  analytics: {
    countCompletedOrders: (target: string) => [
      'query',
      'analytics',
      'completed-orders',
      { target },
    ],
    avgPrepTime: (target: string) => [
      'query',
      'analytics',
      'avg-prep-time',
      { target },
    ],
    countActiveOrders: () => ['query', 'analytics', 'active-orders'],
    topSellingItems: () => ['query', 'analytics', 'top-selling-items'],
    topActiveUsers: () => ['query', 'analytics', 'top-active-users'],
    ordersByCategory: (target: string) => [
      'query',
      'analytics',
      'orders-by-category',
      { target },
    ],
    ordersAndRevenue: (target: string) => [
      'query',
      'analytics',
      'orders-and-revenue',
      { target },
    ],
    waiterSelfPerformance: (target: string, waiterId?: number) => [
      'query',
      'analytics',
      'waiter-self-performance',
      { target, waiterId },
    ],
    waiterPerformance: (target: string) => [
      'query',
      'analytics',
      'waiter-performance',
      { target },
    ],
    waiterPerformanceSummary: () => [
      'query',
      'analytics',
      'waiter-performance-summary',
    ],
    totalRevenue: () => ['query', 'analytics', 'total-revenue'],
  },
}
