/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ForgetPasswordRouteImport } from './routes/forget-password'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthDashboardRouteRouteImport } from './routes/_auth/dashboard.route'
import { Route as AuthDashboardIndexRouteImport } from './routes/_auth/dashboard.index'
import { Route as AuthDashboardSettingsRouteImport } from './routes/_auth/dashboard/settings'
import { Route as AuthDashboardProfileRouteImport } from './routes/_auth/dashboard/profile'
import { Route as AuthDashboardNotificationRouteImport } from './routes/_auth/dashboard/notification'
import { Route as AuthDashboardActivityRouteImport } from './routes/_auth/dashboard/activity'
import { Route as AuthDashboardUsersIndexRouteImport } from './routes/_auth/dashboard/users/index'
import { Route as AuthDashboardMenuIndexRouteImport } from './routes/_auth/dashboard/menu/index'
import { Route as AuthDashboardUsersIdRouteImport } from './routes/_auth/dashboard/users/$id'

const ForgetPasswordRoute = ForgetPasswordRouteImport.update({
  id: '/forget-password',
  path: '/forget-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDashboardRouteRoute = AuthDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardIndexRoute = AuthDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthDashboardRouteRoute,
} as any)
const AuthDashboardSettingsRoute = AuthDashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthDashboardRouteRoute,
} as any)
const AuthDashboardProfileRoute = AuthDashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthDashboardRouteRoute,
} as any)
const AuthDashboardNotificationRoute =
  AuthDashboardNotificationRouteImport.update({
    id: '/notification',
    path: '/notification',
    getParentRoute: () => AuthDashboardRouteRoute,
  } as any)
const AuthDashboardActivityRoute = AuthDashboardActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthDashboardRouteRoute,
} as any)
const AuthDashboardUsersIndexRoute = AuthDashboardUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthDashboardRouteRoute,
} as any)
const AuthDashboardMenuIndexRoute = AuthDashboardMenuIndexRouteImport.update({
  id: '/menu/',
  path: '/menu/',
  getParentRoute: () => AuthDashboardRouteRoute,
} as any)
const AuthDashboardUsersIdRoute = AuthDashboardUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => AuthDashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forget-password': typeof ForgetPasswordRoute
  '/dashboard': typeof AuthDashboardRouteRouteWithChildren
  '/dashboard/activity': typeof AuthDashboardActivityRoute
  '/dashboard/notification': typeof AuthDashboardNotificationRoute
  '/dashboard/profile': typeof AuthDashboardProfileRoute
  '/dashboard/settings': typeof AuthDashboardSettingsRoute
  '/dashboard/': typeof AuthDashboardIndexRoute
  '/dashboard/users/$id': typeof AuthDashboardUsersIdRoute
  '/dashboard/menu': typeof AuthDashboardMenuIndexRoute
  '/dashboard/users': typeof AuthDashboardUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forget-password': typeof ForgetPasswordRoute
  '/dashboard/activity': typeof AuthDashboardActivityRoute
  '/dashboard/notification': typeof AuthDashboardNotificationRoute
  '/dashboard/profile': typeof AuthDashboardProfileRoute
  '/dashboard/settings': typeof AuthDashboardSettingsRoute
  '/dashboard': typeof AuthDashboardIndexRoute
  '/dashboard/users/$id': typeof AuthDashboardUsersIdRoute
  '/dashboard/menu': typeof AuthDashboardMenuIndexRoute
  '/dashboard/users': typeof AuthDashboardUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/forget-password': typeof ForgetPasswordRoute
  '/_auth/dashboard': typeof AuthDashboardRouteRouteWithChildren
  '/_auth/dashboard/activity': typeof AuthDashboardActivityRoute
  '/_auth/dashboard/notification': typeof AuthDashboardNotificationRoute
  '/_auth/dashboard/profile': typeof AuthDashboardProfileRoute
  '/_auth/dashboard/settings': typeof AuthDashboardSettingsRoute
  '/_auth/dashboard/': typeof AuthDashboardIndexRoute
  '/_auth/dashboard/users/$id': typeof AuthDashboardUsersIdRoute
  '/_auth/dashboard/menu/': typeof AuthDashboardMenuIndexRoute
  '/_auth/dashboard/users/': typeof AuthDashboardUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forget-password'
    | '/dashboard'
    | '/dashboard/activity'
    | '/dashboard/notification'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/users/$id'
    | '/dashboard/menu'
    | '/dashboard/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forget-password'
    | '/dashboard/activity'
    | '/dashboard/notification'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard'
    | '/dashboard/users/$id'
    | '/dashboard/menu'
    | '/dashboard/users'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/forget-password'
    | '/_auth/dashboard'
    | '/_auth/dashboard/activity'
    | '/_auth/dashboard/notification'
    | '/_auth/dashboard/profile'
    | '/_auth/dashboard/settings'
    | '/_auth/dashboard/'
    | '/_auth/dashboard/users/$id'
    | '/_auth/dashboard/menu/'
    | '/_auth/dashboard/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ForgetPasswordRoute: typeof ForgetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/forget-password': {
      id: '/forget-password'
      path: '/forget-password'
      fullPath: '/forget-password'
      preLoaderRoute: typeof ForgetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard/': {
      id: '/_auth/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthDashboardIndexRouteImport
      parentRoute: typeof AuthDashboardRouteRoute
    }
    '/_auth/dashboard/settings': {
      id: '/_auth/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthDashboardSettingsRouteImport
      parentRoute: typeof AuthDashboardRouteRoute
    }
    '/_auth/dashboard/profile': {
      id: '/_auth/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthDashboardProfileRouteImport
      parentRoute: typeof AuthDashboardRouteRoute
    }
    '/_auth/dashboard/notification': {
      id: '/_auth/dashboard/notification'
      path: '/notification'
      fullPath: '/dashboard/notification'
      preLoaderRoute: typeof AuthDashboardNotificationRouteImport
      parentRoute: typeof AuthDashboardRouteRoute
    }
    '/_auth/dashboard/activity': {
      id: '/_auth/dashboard/activity'
      path: '/activity'
      fullPath: '/dashboard/activity'
      preLoaderRoute: typeof AuthDashboardActivityRouteImport
      parentRoute: typeof AuthDashboardRouteRoute
    }
    '/_auth/dashboard/users/': {
      id: '/_auth/dashboard/users/'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof AuthDashboardUsersIndexRouteImport
      parentRoute: typeof AuthDashboardRouteRoute
    }
    '/_auth/dashboard/menu/': {
      id: '/_auth/dashboard/menu/'
      path: '/menu'
      fullPath: '/dashboard/menu'
      preLoaderRoute: typeof AuthDashboardMenuIndexRouteImport
      parentRoute: typeof AuthDashboardRouteRoute
    }
    '/_auth/dashboard/users/$id': {
      id: '/_auth/dashboard/users/$id'
      path: '/users/$id'
      fullPath: '/dashboard/users/$id'
      preLoaderRoute: typeof AuthDashboardUsersIdRouteImport
      parentRoute: typeof AuthDashboardRouteRoute
    }
  }
}

interface AuthDashboardRouteRouteChildren {
  AuthDashboardActivityRoute: typeof AuthDashboardActivityRoute
  AuthDashboardNotificationRoute: typeof AuthDashboardNotificationRoute
  AuthDashboardProfileRoute: typeof AuthDashboardProfileRoute
  AuthDashboardSettingsRoute: typeof AuthDashboardSettingsRoute
  AuthDashboardIndexRoute: typeof AuthDashboardIndexRoute
  AuthDashboardUsersIdRoute: typeof AuthDashboardUsersIdRoute
  AuthDashboardMenuIndexRoute: typeof AuthDashboardMenuIndexRoute
  AuthDashboardUsersIndexRoute: typeof AuthDashboardUsersIndexRoute
}

const AuthDashboardRouteRouteChildren: AuthDashboardRouteRouteChildren = {
  AuthDashboardActivityRoute: AuthDashboardActivityRoute,
  AuthDashboardNotificationRoute: AuthDashboardNotificationRoute,
  AuthDashboardProfileRoute: AuthDashboardProfileRoute,
  AuthDashboardSettingsRoute: AuthDashboardSettingsRoute,
  AuthDashboardIndexRoute: AuthDashboardIndexRoute,
  AuthDashboardUsersIdRoute: AuthDashboardUsersIdRoute,
  AuthDashboardMenuIndexRoute: AuthDashboardMenuIndexRoute,
  AuthDashboardUsersIndexRoute: AuthDashboardUsersIndexRoute,
}

const AuthDashboardRouteRouteWithChildren =
  AuthDashboardRouteRoute._addFileChildren(AuthDashboardRouteRouteChildren)

interface AuthRouteChildren {
  AuthDashboardRouteRoute: typeof AuthDashboardRouteRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRouteRoute: AuthDashboardRouteRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ForgetPasswordRoute: ForgetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
